### ISSUE TITLE
[BUG] No exception pops up when requesting non-existent key with resourceBundle parameter in getMessage() API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1038]
**Describe the bug**
Build with commit: 2d927753ef1accb802bd746996856aeb9aa614e1
No exception pops up when requesting non-existent key with resourceBundle parameter in getMessage() API.

**To Reproduce**
1. Get message's translation with 
String msg = tm.getMessage("offlineBundles.PropertiesFileComponent.messages", DE, "PropertiesFileComponentOffline", "NonExistentKey");

Notes: Has relative messages.properties file under offlineBundles.PropertiesFileComponent path, but there is not key "NonExistentKey" in that file.		

**Expected behavior**
Has such exception to warn user here is no the translation with ar locale, just similar with getMessage() without resourceBundle parameter:
"Failed to get any message for key: NonExistentKey of component PropertiesFileComponentOffline, requested locale: de"

**Comment by jessiejuachon** [comment]
Parent issue: https://github.com/vmware/singleton/issues/860
Parent PR: https://github.com/vmware/singleton/pull/940/files

Solution: Add a try catch around `ResourceBundle.getBundle(resourceBundle).getString(key)` which is inside TranslationMessage.getMessageWithArgs(String resourceBundle, final Locale locale, final String component, final String key, final Object args)

**Comment by lyiyu66** [comment]
The issue is fixed with commit 9043f611ce6802685000aaa048f6a6164e267ee4.
