### ISSUE TITLE
[BUG] [l10n] Data cannot be restored if grm.server.url is invalid

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1059]
**Describe the bug**
The collected data should be stored into Cache first to avoid data lost. 

**To Reproduce**
1. Start latest Singleton l10n Service build
2. Update configuration file with invalid grm.server.url (or grm.server is down) and valid vip.server.url
3. Go to any API to do source collection
4. Stop Singleton l10n Service and update configuration with a valid grm.server.url
5. Check the source collection result:
```
1. The data is saved into local bundle file successfully;
2. The same data is failed to send to grm.server
3. The same data is failed ton send to vip.server
```

**Expected behavior**
If the data is failed to grm.server, it should be saved into cache, and after grm.server is avalible or valid, the data in cache should be sent to grm.server and vip.server successfully.

**Comment by tigershi** [comment]
Because no recover handling mechanism when source send to grm failure, it will block when send to GRM failure. It will be fixed in PR https://github.com/vmware/singleton/pull/1427
