### ISSUE TITLE
[BUG] [Service][S3] [Product-Based API] Failed to get translation if translation existing in some componets

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1060]
**Describe the bug**
In Singleton Service S3 build, if translation is ready for some components, not avaible for some components, it will be failed to return translation for the whole request product/version.
This issue is not reproduced in Singleton Service bundle build.

**To Reproduce**
1. Start latest Singleton Service S3 build;
2. Go to product-based API *GET /i18n/api/v2/translation/products/{productName}/versions/{version} Get the product's translation*
3. Bundle data existing
```
Product: Testing
version: 1.0.0
component: default, noexisting
support locale: en, de, ja
bundle: default-en, default-de, default-ja, noexisting-en
```
4. Request parameters:
```
Product: Testing
version: 1.0.0
locales: de
```
Responses:
```
{
  "response": {
    "code": 404,
    "message": "Faild to get translation from data for Testing/1.0.0",
    "serverTime": ""
  },
  "signature": "",
  "data": ""
}
```
**Expected behavior**
The existing translation can be returned well, and null for no existing translation component.

**Comment by LilyLi2019** [comment]
Hi @tigershi ,
It blocked product issue: https://jira.eng.vmware.com/browse/CSP-34454.
Please take higher priority for this issue.
Thanks.

**Comment by tigershi** [comment]
I am working on it
