### ISSUE TITLE
[REQUIREMENT][Java Client] Make readTimeout property configurable

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#1070]
**Is your feature request related to a problem? Please describe.**
We want to use isAvailable(final String component, final String key, final Locale locale) method, but there are many records in our component and I see that the isAvailable method tries to get all the records for the component with param chechTransaltionStatus=true, which leads to read time out and we always get false as a result of the isAvailable method. Request which leads to read timeout:
https://<singleton url>/i18n/api/v2/translation/products/<product name>/versions/1.0.0/locales/zh-CN/components/templates?pseudo=false&checkTranslationStatus=true

**Describe the solution you'd like**
My question is can we configure the readTimeout property of the HttpURLConnection on our side, because I see that it is set to 5 seconds now?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by huihuiw01** [comment]
After reproduce the issue of SSBackend, find their component is very big, including almost 50, 000 keys, much more than our suggested amount 5, 000. So communicate this with @georgievara, suggest them split the component, they create their JIRA task to track this, and plan to execute it in the next quarter. And for this quarter's release, they have found a workround.
