### ISSUE TITLE
[BUG] [Service][authentication] token will be expired if a new token generated by same parameters 

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1113]
**Describe the bug**
In Singleton JAVA service, for authentication APIs, an old *token* will be expired after a new *token* generated by same *appId* and *authorization*, even if it's not over expired time.

**To Reproduce**
1. Start latest Singleton Java Service
2. Go to authorization APIs
3. Go to API: *POST /auth/token generateToken*, to get a token1
4. Go to any v2 API with above *appId* and *token1*: `The correct response data will returned`
5. Go back to generateToken api to get another new token2
6. Go to any v2 API with request *appId* and *token2*: `The correct response data will returned`
7. Go to any v2 API with request 'appId' and *token1*: 
```
{
  "response": {
    "code": 401,
    "message": "The authorization fails, please validate the token!",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Expected behavior**
The correct response data should be returned correctly.

**Comment by tigershi** [comment]
we don't think  this is a bug.

**Comment by tigershi** [comment]
we can't reproduce it and I have discussed with Nannan. It is not a bug.
