### ISSUE TITLE
[BUG] [Service] [authentication] Change all 'Authorization' to 'authentication' in swagger-ui

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1114]
**Describe the bug**
Please change all *'Authorization'* or *'authorised'* to *'authentication'* in Singleton code.

**Comment by nannany00** [comment]
Please change all words value, including the word in swagger-ui and response, example: 
![image](https://user-images.githubusercontent.com/50618120/120583126-3af56f80-c460-11eb-93c4-62a079eac0fc.png)

**Comment by JiLiang888** [comment]
Failed
![image](https://user-images.githubusercontent.com/82644009/121493465-723cc100-ca0a-11eb-9d22-ec729cdad950.png)
![image](https://user-images.githubusercontent.com/82644009/121493592-900a2600-ca0a-11eb-9ad7-105ffefa91df.png)

**Comment by JiLiang888** [comment]
Part Fail

When  appid/token is wrong, authorization also diaplay 
![image](https://user-images.githubusercontent.com/82644009/122867845-b90cae00-d35c-11eb-96f4-7a034cb8109e.png)

**Comment by JiLiang888** [comment]
pass
![image](https://user-images.githubusercontent.com/82644009/123906536-f00b4100-d9a6-11eb-8e3b-b04b99fd47a4.png)
![image](https://user-images.githubusercontent.com/82644009/123906577-04e7d480-d9a7-11eb-9113-f15635c4bbdd.png)
![image](https://user-images.githubusercontent.com/82644009/123906627-19c46800-d9a7-11eb-8de1-ceb3d2f997d7.png)
