### ISSUE TITLE
[BUG] [Go Service]Imprecise message when language field is left as empty in /combination/translationsAndPattern POST API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1146]
**Describe the bug**
Build with commit 3fb0a4761a3dc189e0db3d40048ae065bb40408b
Imprecise message when language field is left as empty in /combination/translationsAndPattern POST API.

**To Reproduce**
1. Go to /combination/translationsAndPattern POST API.
2. Input below info to data field:
```
{
  "combine": 1,
  "components": [
    "default"
  ],
  "language": "",
  "productName": "vmware2018",
  "pseudo": "false",
  "region": "CN",
  "scope": "dates",
  "version": "1.1.0"
}
```
3. See the response:
```
{
  "response": {
    "code": 400,
    "message": "Incorrect language(only allows letter, number, dot, underline, dash)"
  }
}
```

**Expected behavior**
Should warn about language field is required, can't accept null and empty.

**Comment by Xiaochao8** [comment]
Currently all the interfaces follow this rule not checking if the filed is required. To align with other interfaces, won't fix this.
