### ISSUE TITLE
[BUG] [Service] Unit test failed

### ISSUE THREAD

**Issue by WisdomLuo** [vmware/singleton#1219]
**Describe the bug**
Singleton master branch unit tests failed.

**To Reproduce**
1. Go to directory g11n-ws
2. Run command ./gradlew test --console=plain

**Screenshots**
![image](https://user-images.githubusercontent.com/40684088/126256306-780e59b9-48d0-4a1f-98af-ff8699346a3d.png)

**Comment by huihuiw01** [comment]
This bug has been fixed by PR #1218 owned by @tigershi.
