### ISSUE TITLE
[REQUIREMENT]Change configuration support to allow outside IConfig object. And allow enumeration of components from resx paths. And allow one time connection with Singleton service.

### ISSUE THREAD

**Issue by jin-jasper** [vmware/singleton#1224]
1. Change configuration support to allow outside IConfig object. 
    IConfig I18N.LoadConfigFromText(text);
    IConfig I18N.LoadConfig(resourceBaseName, assembly, configResourceName, IConfig outsideConfig);

2. Allow enumeration of components from resx paths.
    component_enumerate: auto

3. Allow one time connection with Singleton service.
    enable_expire: false

**Comment by dleng-vmware** [comment]
After testing, the new features worked normally
