### ISSUE TITLE
[CSharp Client] 'load_on_startup' is invalid when it's in pure offline mode.

### ISSUE THREAD

**Issue by jin-jasper** [vmware/singleton#1228]
**Describe the bug**
'load_on_startup' is invalid when it's in pure offline mode.

**To Reproduce**
1. Set configuration file to pure offline mode
2. Set 'load_on_startup' to true
3. Startup and access 'zh-CN' messages.

**Expected behavior**
A translation of Chinese is displayed.

**Comment by dleng-vmware** [comment]
Bug not fully fixed, it does not take effect in the offline disk mode

**Comment by dleng-vmware** [comment]
The bug fixed in commit f68c22c
