### ISSUE TITLE
[BUG] [S3 service]When vesion has no previous version,response code should be 404

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1258]
**Describe the bug**
When vesion has no previous version,response code should be 404 in below apis
\Service\API\V2\translation-product-api\getSupportedLocalesUsingGET_1
\Service\API\V2\locale-api\getDisplayLanguagesListUsingGET

**To Reproduce**
\Service\API\V2\locale-api\getDisplayLanguagesListUsingGET
productName=vmware2018;version=0.0.1;displayLanguage=ja
**Response Json**: '{"response":{"code":200,"message":"OK","serverTime":""},"signature":"","data":{"languages":[],"displayLanguage":"ja","version":"0.0.1","productName":"vmware2018"}}'

**Expected behavior**
{
  "response": {
    "code": 404,
    "message": "Failed to get locale list for vmware2018/0.0.1",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}

**Screenshots**
If applicable, add screenshots to help you explain your issue

**Additional context**

**Comment by tigershi** [comment]
@JiLiang888   I can't find any url is \Service\API\V2\translation-product-api\getSupportedLocalesUsingGET_1 or \Service\API\V2\locale-api\getDisplayLanguagesListUsingGET in singleton service
but url /i18n/api/v2/locale/supportedLanguageList and 
/i18n/api/v2/translation/products/{productName}/versions/{version}/localelist
in singleton service

**Comment by tigershi** [comment]
I have confirmed it that url /i18n/api/v2/locale/supportedLanguageList and
/i18n/api/v2/translation/products/{productName}/versions/{version}/localelist have same response in same request parameter. Because of the url have version fallback feature, the response code is 200
