### ISSUE TITLE
[BUG] [Lite Service] When productname is not setted in bundle.json ,reponse should be 400,not 404.

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1261]
**Describe the bug**
When productname is not setted in bundle.json ,reponse should be 400,not 404.

**To Reproduce**
http://localhost:8095/i18n/api/v2/translation/products/**VMwareVIPaaa**/versions/1.1.0?pseudo=false
![image](https://user-images.githubusercontent.com/82644009/129339977-21f67633-0a31-46f7-8e62-2485dc39500a.png)

**Expected behavior**
{
  "code" : 400,
  "message" : "The product 'VMwareVIPaaa' is NOT supported yet!",
  "serverTime" : ""
}

**Additional context**

**Comment by tigershi** [comment]
The lite service doesn't have feature that validate productname in bundle.json

**Comment by tigershi** [comment]
please check the issue： https://github.com/vmware/singleton/issues/936

**Comment by JiLiang888** [comment]
Not  bug
