### ISSUE TITLE
[BUG] [Ruby Client]Fail to start app when an empty folder under source path

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1274]

**Comment by linr211** [comment]
This is by design, meaning for an component, it's required to have default file under it, otherwise it will failed to start app.

**Comment by Xiaochao8** [comment]
It doesn't make sense to stop the application just because an empty folder.

**Comment by lyiyu66** [comment]
Checked with build 0.7.0.36 with commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313, the issue is fixed in below scenario: no source file in component2

source directory:
source
 -component1
   -default.yml
 -component2
 -component3
   -default.yml
