### ISSUE TITLE
[BUG] [Ruby Client]Wrong to read system files as source

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1276]
When starting app, ruby client reads some system files for source.

The error message is as below:
Uncaught exception: Not a directory @ rb_sysopen - ./config/sources/.DS_Store/source.yml
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/singleton-ruby-0.1.0/lib/sgtn-client/api/source.rb:56:in `read'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/singleton-ruby-0.1.0/lib/sgtn-client/api/source.rb:56:in `read_yml'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/singleton-ruby-0.1.0/lib/sgtn-client/api/source.rb:33:in `block in loadBundles'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/singleton-ruby-0.1.0/lib/sgtn-client/api/source.rb:31:in `each'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/singleton-ruby-0.1.0/lib/sgtn-client/api/source.rb:31:in `loadBundles'
	/Users/vip/Projects/cloudpercept/lib/g11n/g11n.rb:9:in `<module:G11n>'
	/Users/vip/Projects/cloudpercept/lib/g11n/g11n.rb:3:in `<top (required)>'
	/Users/vip/Projects/cloudpercept/config/application.rb:15:in `require_relative'
	/Users/vip/Projects/cloudpercept/config/application.rb:15:in `<top (required)>'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/railties-3.2.22.15/lib/rails/commands.rb:53:in `require'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/railties-3.2.22.15/lib/rails/commands.rb:53:in `block in <top (required)>'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/railties-3.2.22.15/lib/rails/commands.rb:50:in `tap'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/gems/railties-3.2.22.15/lib/rails/commands.rb:50:in `<top (required)>'
	/Users/vip/Projects/cloudpercept/script/rails:6:in `require'
	/Users/vip/Projects/cloudpercept/script/rails:6:in `<top (required)>'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/bin/rdebug-ide:23:in `load'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/bin/rdebug-ide:23:in `<main>'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/bin/ruby_executable_hooks:22:in `eval'
	/Users/vip/.rvm/gems/ruby-2.5.5@cp/bin/ruby_executable_hooks:22:in `<main>'

**Comment by linr211** [comment]
As the valid default bundle is required to startup the app, the path /config/sources/.DS_Store should be valid, so i think it's not an issue.

**Comment by Xiaochao8** [comment]
The `.DS_Store` folder is a system folder, we shouldn't read bundles within it.

**Comment by Xiaochao8** [comment]
Can't reproduce with commit b4a22fc735474eaee65942317dc27480f8c6d8a5
Hence close it.
