### ISSUE TITLE
[BUG] [Ruby Client]An error occurs when loading sources

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1279]
NameError - undefined local variable or method `itmes' for SgtnClient::Source:Class
Did you mean?  items:
  singleton-ruby (0.1.2) lib/sgtn-client/api/source.rb:37:in `getSources'
  singleton-ruby (0.1.2) lib/sgtn-client/api/translation.rb:58:in `getStrings'

**Comment by linr211** [comment]
fixed it in v0.1.3
