### ISSUE TITLE
[BUG] [Ruby Client]L2 functions should not only support time conversion to UTC time zones.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1282]
**Describe the bug**
L2 functions should have custom time zone parameters to support time zone conversion, not just to UTC time zones.
Now, the current version, even if not has the Time zone in method 'to_full_s', It should also support the default operating system time zone.

**To Reproduce**
1. d = DateTime.new(2017,11,20,13,39,24,"08:00")  ##------>("08:00" represents the offset of the input time, d form : 2017-11-20T13:39:24+08:00)
2. Result = d.to_full_s(:en)
**Result return "Monday, November 20, 2017 at 5:39:24 AM Coordinated Universal Time"**

**Expected behavior**

**Screenshots**
It should Convert to the default OS time zone, Lisk this: Monday, November 20, 2017 at 1:39:24 PM GMT+8.

**Comment by linr211** [comment]
The APIs haven't support timezone yet, will add the support later.
