### ISSUE TITLE
[BUG] [Ruby Client] The parameter 'locale' of L2 function not support '-' symbol (such as zh-CN or en-US).

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1283]
**Describe the bug**
The parameter 'locale' of L2 function not support '-' symbol (such as zh-CN or en-US or zh-Hans).

**To Reproduce**
1. d = DateTime.new(2018,9,18,7,20,34)
2. Result1 = d.to_full_s(:zh-Hans)
**Throw an error : "uninitialized constant Hans (NameError)"**

**Expected behavior**
Convert to Chinese full format time

**Comment by linr211** [comment]
As Ruby's syntax doesn't support "-" in :zh-Hans, so it's not a bug.

**Comment by dleng-vmware** [comment]
But the other methods on the Ruby client support zh-Hans, so don't you need a uniform format here？

**Comment by dleng-vmware** [comment]
after test team discuss ,the format d.to_full_s(:'zh-Hans') and d.to_full_s('zh-Hans') can be execute successfully.So it's not a bug
