### ISSUE TITLE
[BUG] [Ruby Client] Can't replace placeholder "{0}, {1}" by getString_f()

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1284]
**Describe the bug**
Can't replace placeholder "{0}, {1}" by getString_f()
**GetString_f() should replace placeholder "{0}" rather than "%s",because the placeholders in the l10n bundle are {string}**

**To Reproduce**
1. Set the value of key "key1" be "{0} {1} TEST VALUE"
2.  SgtnClient::Source.loadBundles("default")
     result = SgtnClient::Translation.getString_f("JAVA", "key1",["a1","a2"], "de")
**the result return "{0} {1} TEST VALUE"**

**Expected behavior**
Result should be "a1 a2 TEST VALUE"

**Comment by linr211** [comment]
The correct usage is '%{number}$s', e.g.‘%2$s, welcome login %1$s’, so it's not a bug.

**Comment by Xiaochao8** [comment]
Please verify it in Ruby way rather than ICU way.

**Comment by lyiyu66** [comment]
Thanks for comment. In this case, the bug is not a bug. Hence closing.
