### ISSUE TITLE
[BUG] [Ruby Client]Can't get language string from online bundle in online mode when the local source file is language.yml

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1293]
**Describe the bug**
Can't get language string from online bundle in online mode when the local source file is language.yml
Such as: en.yml , de.yml

**To Reproduce**
1. Set source file as en.yml in source bundle
2. SgtnClient::Source.loadBundles("en")
3. result1 = SgtnClient::Translation.getString("about", "about.message", "en")
**result1 return the string in en.yml**

**Expected behavior**
result1 should return string of online en file rather than the string in en.ym

**Comment by Xiaochao8** [comment]
After source comparison, if the strings of same key are different between source bundle and translation bundle of source locale. String in source bundle will be used.
