### ISSUE TITLE
[REQUIREMENT]Add Code in build.gradle 

### ISSUE THREAD

**Issue by renligeng** [vmware/singleton#1348]
To generate sources jar and javadoc jar package by using gradle, need to add following task in build.gradle.

build.gradle path=g11n-ws/tools/tool-cldr-extractor/build.gradle

```
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    archiveClassifier = 'sources'
}
 
task javadocJar(type: Jar) {
    from javadoc
    archiveClassifier = 'javadoc'
}

**Comment by InaSong** [comment]
Blocked by the Spring Boot Upgrade, not started yet.

**Comment by lyiyu66** [comment]
Checked with latest commit, behavior of sources jar and javadoc jar package generation as below:
java client(03fe7e4769def0e27b56f1f5af127a4a45298e3c): Passed
![image](https://user-images.githubusercontent.com/51813046/173803670-a0cc07e1-ec23-4089-aa66-fad483cb9d87.png)

java service(50655e86f344be19e39c731e8d20ad4678ac956c): Failed
![image](https://user-images.githubusercontent.com/51813046/173803409-814bc502-606f-4cf3-a144-30bc8375bdc7.png)

cldr pattern(7a86308eb24190706efab6d5e194fe04fdc2eee4): Failed
![image](https://user-images.githubusercontent.com/51813046/173803310-d14ac02e-ae2e-4522-bf96-d8c7779fcedd.png)

**Comment by tigershi** [comment]
singleton and  l10n service generate sources jar and javadoc jar have fixed in PR: https://github.com/vmware/singleton/issues/1701

**Comment by lyiyu66** [comment]
Checked with commit 5a7ddde8c85c1cbc81779cd8cec3c182d12dcd85, cldr pattern lib is fixed.
For issue of service lib, it is tracked with https://github.com/vmware/singleton/issues/1701
