### ISSUE TITLE
[BUG] [Ruby Client]Plural can't use fallback locale when no translation is available for requested locale. 

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1379]
**Describe the bug**
commit: b88b2e822377b4c8828d45998e5cfbf06a80c045
Plural can't use fallback locale when no translation is available for requested locale. 

**To Reproduce**
plural rule of locale "en":
```
<pluralRules locales="ast ca de en et fi fy gl ia io ji lij nl sc scn sv sw ur yi">
            <pluralRule count="one">i = 1 and v = 0 @integer 1</pluralRule>
            <pluralRule count="other"> @integer 0, 2~16, 100, 1000, 10000, 100000, 1000000, … @decimal 0.0~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
        </pluralRules>
```
plural rule of locale "da"
```
<pluralRules locales="da">
            <pluralRule count="one">n = 1 or t != 0 and i = 0,1 @integer 1 @decimal 0.1~1.6</pluralRule>
            <pluralRule count="other"> @integer 0, 2~16, 100, 1000, 10000, 100000, 1000000, … @decimal 0.0, 2.0~3.4, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, …</pluralRule>
        </pluralRules>
```
string in messages_en.json file:
```
"pluralsstr1" : "%<{ \"cat_count\": { \"one\": \"there is one cat in the room\", \"other\": \"there are %{cat_count} cats in the room\" } }>",
```
Method in .rb file:
```
@NonLocale_Result0 = SgtnClient::Translation.getString("JAVA", "pluralsstr1", "da").to_plural_s("da", { :cat_count =>  1.6})
```

**Actual behavior**
The translation is using "en"(since en content in defined .yml file) but the plural still use "da".
@NonLocale_nofrtranslation_Result0: there is one cat in the room

**Expected behavior**
The translation and plural should use the same locale when locale fallback to keep consistence.
@NonLocale_nofrtranslation_Result0: there are 1.7 cats in the room

**Comment by linr211** [comment]
Seems it has to combine getString with to_plural_s, will try to fix it by this way.

**Comment by lyiyu66** [comment]
Verified with build 0.7.0.18
The issue about getString() interface(for getting common strings without placeholder) has been fixed with new interface getString_p().
The fallback issue of the strings with placeholder will be tracked in another issue.
