### ISSUE TITLE
[BUG][Angular Client] Issue when packaging the library from source code

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1440]
Bug reported by Jessie:

To replicate:

- Build the angular client library from source code.

1. Package it using "npm pack", and you will get the following error:

```
$ npm pack
npm ERR! package.json requires a "name" field
```
To get away from the above error, add a "name" field and run "npm pack" again.
2. Use the .tgz file in a sample angular application.
In sample application's package.json, add the dependency to the .tgz created in previous step:
`"@singleton-i18n/angular-client": "file:../g11n-angular-client/singleton-i18n-angular-client-0.1.0.tgz"`
3. Run 'npm i' in sample application.

Issues:

1. "npm pack' does not work and produces the "name" filed error in Step 1.
2. After "npm i" in sample app in Step 3, cannot find the following module even if present in node_modules folder:
@singleton-i18n/angular-client
3. The steps above are from the sample app's [README](https://github.com/vmware/singleton/tree/g11n-angular-client#readme). It should be updated with correct steps.

**Comment by jessiejuachon** [comment]
@InaSong , since the bug is only happening when packaging the client library locally, the priority could pehaps be lower.

**Comment by sjiang-cb** [comment]
Not a bug, we will update related documentation when having additional requirements
