### ISSUE TITLE
[Documentation][Java Client] Improve current Java client document to decribe how to construct the source string

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1441]

**Comment by lyiyu66** [comment]
Checked with 0.6.1 doc in below url about new feature, the css looks a litte wired.
https://vmware.github.io/singleton/docs/overview/singleton-sdk/resources/java-client/0.6.1/javadoc/com/vmware/vipclient/i18n/base/instances/TranslationMessage.html
![image](https://user-images.githubusercontent.com/51813046/173736497-f21d0afc-af21-4548-add6-40fa3135ef37.png)

**Comment by lyiyu66** [comment]
![image](https://user-images.githubusercontent.com/51813046/195549178-851ff216-b134-4ebe-bd64-39095086f42c.png)
