### ISSUE TITLE
[Devops] Add Performance Testing in CI

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1449]
The action item of "Performance issue impacts VCF delivery" from Log4j post-mortem

**Comment by junw-33455432** [comment]
@mabeijing Hi, it seems the performance test failed in the Actions CI, here is the detailed log: https://github.com/vmware/singleton/actions/runs/3935003562/jobs/6730290823 could you help to check?

**Comment by mabeijing** [comment]
please use dockerfile in performance directory.
and modify task. copy to the same folder as singleton-manager.jar
