### ISSUE TITLE
[Singleton Service s3] [Get drop version info] unexpected error code when drop info no exist

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#146]
Singleton Service API in s3 build:
GET /i18n/api/v2/translation/products/{productName}/versions/{version}/versioninfo (Get drop version info)

This API is used to provide the translation update version.

------------------
This issue is:
When request the drop version info for a product without drop version existing, it will return unexpected error like below:
```
{
  "response": {
    "code": 520,
    "message": "The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: AB264939503A8555; S3 Extended Request ID: 96vvl9ECA/mNEro2/WsaN0756pp5xylh8U1LTQHan3ZQGz3tjG5pNX6h8k6JcapgsGDoOcxU+hY=)",
    "serverTime": ""
  },
  "signature": "",
  "data": ""
}
```

Suggestion Result like:
```
{
  "response": {
    "code": 404,
    "message": "Failed to get drop version info for [productName]/[version]",
    "serverTime": ""
  },
  "signature": "",
  "data": ""
}
```

**Comment by tigershi** [comment]
the version file can't push to S3 file system
