### ISSUE TITLE
[Security] Review and Assign Code Scanning Issues for Go Service (28 issues)

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1468]
Please review the code scanning issues for Go service (28 issues): https://github.com/vmware/singleton/security/code-scanning?query=is%3Aopen+branch%3Ag11n-go-service

Check points:
1. Please figure out if the issue need fix
2. If fixing needed, please click "create issue" and assign the issue to specific team members
3. If no need to fix, please close the issue with a correct dismiss reason

**Comment by Xiaochao8** [comment]
Checked these issues, they are all false. Will mark them as FAKE.
