### ISSUE TITLE
[Security] Review and Assign Code Scanning Issues for Java Service (46 issues)

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1469]
Please review the code scanning issues for Java service (46 issues): https://github.com/vmware/singleton/security/code-scanning?query=is%3Aopen+branch%3Amaster

Check points:
Please figure out if the issue need fix
If fixing needed, please click "create issue" and assign the issue to specific team members
If no need to fix, please close the issue with a correct dismiss reason

**Comment by tigershi** [comment]
we have discussed it. As a result, we decide to fix the critical issues first.
