### ISSUE TITLE
[BUG] [Ruby Client]Doesn't support SupportedLocaleList API and leverage it for avoiding needless http requests.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1473]
**Describe the bug**
Doesn't support fetch SupportedLocaleList and leverage it for avoiding needless http requests.

**To Reproduce**
1. Run any Ruby application that uses the Singleton Ruby client library.
2. Send a request to the client application for translations in an unsupported language.
3. Notice that for every request in step 2, the client application sends a request to Singleton service to fetch the non-existent translations.

**Expected behavior**
1. At startup, the client application should fetch the list of supported languages from Singleton service, and add the list to client-side cache.
2. When a request for translations in an unsupported language is sent to the client application, the Singleton Ruby client library should check the list of supported languages in cache, find that the requested language is not supported, and serve the source language.
3. Simultaneously, the Singleton ruby client library should also check if the cached list of supported languages has expired. If yes, the cache should be refreshed in parallel (parallel thread).

Notes: 

- The above behavior is expected for both single-string (getString) and component-strings (getStrings) queries.
- Implementation of Thread.new in the Ruby client library must be independent of application framework and web server

References: 
Sample of Thread.new:
- https://github.com/jessiejuachon/g11n_locale_service_ruby
- https://github.com/jessiejuachon/g11n-ruby-sample-app

**Comment by lyiyu66** [comment]
The localelist is not fetched at application startup, it will send the request once invoking key/component translation interfaces.

**Comment by Xiaochao8** [comment]
> The localelist is not fetched at application startup, it will send the request once invoking key/component translation interfaces.

Client provides this interface. It's user's responsiblity to call it when necessary.

**Comment by lyiyu66** [comment]
According to the comments above, getting the locale list via the translate call is more flexible, as it ensures that the locale matching workflow can work even if the locale list is not called on initialization (startup), but not vice versa.
Current behavior:
1. getting locale list when invoking translation call
2. send out translation request depends on requested component&locale exists in the available bundle(localelist+componentlist)
3. localelist and componentlist has same cache mechanism with translation
