### ISSUE TITLE
[BUG] [Ruby Client] An error is raised by getString when locale argument is nil.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1476]
**Describe the bug**
 An error is raised by SgtnClient::Translation.getString when locale argument is nil.

**To Reproduce**
1. Use the ruby client in a sample application.
2. In the sample app, trigger a call to `SgtnClient::Translation.getString(component, key, locale)`, with nil value for the locale argument.
3. Error `undefined method 'split' for nil:NilClass`.
Line that throws the error: [locale-util.rb#L21](https://github.com/vmware/singleton/blob/d95aed9ba515bfc45b0c5edd22b472d8cf2eec28/lib/sgtn-client/util/locale-util.rb#L21)

**Expected behavior**
If target locale is either not supported or nil:
a. If list of fallback locales is NOT configured in the client config file, getString must return the source string.
b.  If list of fallback locales is configured in the client config file, getString must use the next fallback locale from the list as target locale, and return the translation. It must go through the list until it is able to return a translation in a fallback locale. If at the end of the list and all fallback locales failed, it must return the source string.

**Comment by lyiyu66** [comment]
PR #1495 is planned to fix this issue, will verify it later.

**Comment by dleng-vmware** [comment]
Now ,Fallback Locales list cannot be configured on the client, so the Expected behavior: b is not supported now.

**Comment by dleng-vmware** [comment]
This bug is fixed
