### ISSUE TITLE
[REQUIREMENT] If the locale is of type Symbol, convert it first to String (i.e. locale.to_s)

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1479]
**Is your feature request related to a problem? Please describe.**
An error is raised by SgtnClient::Translation.getString when locale argument is a Ruby type "Symbol".

1. Use the ruby client in a sample application.
2. In the sample app, trigger a call to `SgtnClient::Translation.getString(component, key, locale)`, with :en (Symbol type) value for the locale argument.
3. Error `undefined method 'split' for nil:NilClass`.
Line that throws the error: [locale-util.rb#L21](https://github.com/vmware/singleton/blob/d95aed9ba515bfc45b0c5edd22b472d8cf2eec28/lib/sgtn-client/util/locale-util.rb#L21)

**Describe the solution you'd like**
If the locale is of type Symbol, convert it first to String (i.e. locale.to_s) so that the above error will not be raised.

**Additional context**
Ruby on Rails' i18n library uses Symbol-type locales, with the default of :en. This Symbol sometimes used and passed to the Signleton client library as is. This feature is to mitigate this behavior.

**Comment by lyiyu66** [comment]
The issue is planed to fix with PR 1479

**Comment by dleng-vmware** [comment]
Fixed
