### ISSUE TITLE
[Singleton Service][Get pattern by language&region] plurals rule should always follow with language

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#148]
Singleton Service API:
GET  /i18n/api/v2/formatting/pattern  (Get pattern from CLDR)

This API is used to provide the pattern data for dates/numbers/currencies/plurals/measurements from CLDR according to the requested language and region.

Plurals rule is related to the translation content, it should always follow with language, as Singleton provides translation by language.

--------------
This issue is:
When the combined locale of language and region is valid, the plurals rule is following the combined locale, not language.

Example:
language=pt; region=PT; scope=plurals

Actual Result is:
it will return the plurals rule of **pt-PT**.

Expected Result is:
it should return the plurals rule of **pt**.

**Comment by nannany00** [comment]
Based on current code, still has issue here:
When language=**pt-PT**, region=**PT**, the plurals rule should be **pt-PT**, not **pt**.

Please help to check.

**Comment by lyiyu66** [comment]
Plurals rule issue has been fixed on current code.
