### ISSUE TITLE
Ruby Client issue: cannot load such file -- coveralls

### ISSUE THREAD

**Issue by vm-mounika** [vmware/singleton#1480]
Pipeline is failing due to Coveralls File issue, please investigate about the Coveralls file, Below is the error i'm seeing :
LoadError:
  cannot load such file -- coveralls
  Did you mean?  coverage
# ./spec/spec_helper.rb:7:in `require'
# ./spec/spec_helper.rb:7:in `<top (required)>'

i updated ruby version  to 3.1.0 then i got different error 
An error occurred while loading spec_helper.
Failure/Error: if @@configurations[:mode] == 'live' and Logging.logger.level == Logger::DEBUG

NameError:
  uninitialized class variable @@configurations in SgtnClient::Config
  Did you mean?  configurations=
# ./lib/sgtn-client/core/config.rb:145:in `logger'
# ./lib/sgtn-client/sgtn-client.rb:70:in `logger'
# ./lib/sgtn-client/sgtn-client.rb:41:in `load'
# ./spec/spec_helper.rb:20:in `<top (required)>'

**Comment by linr211** [comment]
this issue is fixed here: https://github.com/vmware/singleton/pull/1543
