### ISSUE TITLE
[BUG] [Ruby Client] getString returns nil for missing key or source bundle

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1486]
**Describe the bug**
Currently, getString returns nil for missing key. However, per client library spec ([L10n Query](https://confluence.eng.vmware.com/display/GQ/Singleton+Client+Library+-+Caching%2C+Fallback+Mechanism%2C+and+Other+Features#SingletonClientLibraryCaching,FallbackMechanism,andOtherFeatures-L10nQuery)), getString should have raised an error when key does not exist. 

**To Reproduce**
1. Use the Ruby client in any Ruby application
2. Trigger a call to getString API, passing a key that is not in VIP service, and also not in the source file.
3. Error: getString returns nil

**Expected behavior**
getString must raise an error.

**Comment by Xiaochao8** [comment]
Close as a duplicate to #1462
