### ISSUE TITLE
[REQUIREMENT] [Ruby Client] Change log type for missing key errors from 'error' to 'debug'.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1493]
**Is your feature request related to a problem? Please describe.**
The following lines cause a large size of server logs in client applications that passes a nil value for key argument in translation API. This is due to legacy code that uses [Rails-i18n](https://guides.rubyonrails.org/i18n.html).
[log 1](https://github.com/vmware/singleton/blob/d95aed9ba515bfc45b0c5edd22b472d8cf2eec28/lib/sgtn-client/api/translation.rb#L20)
[log 2](https://github.com/vmware/singleton/blob/d95aed9ba515bfc45b0c5edd22b472d8cf2eec28/lib/sgtn-client/api/translation.rb#L32)

**Describe the solution you'd like**
For the above logs, use SgtnClient.logger.debug instead of SgtnClient.logger.error

**Comment by lyiyu66** [comment]
Checked it on commit 6289d12579de534d6ffccd0205f46fe011d076cc
The log type about missing key errors has been changed from "error" to "debug":
getString(), getString_p()
