### ISSUE TITLE
[BUG] [service] Fix critical Scanning Issues for Java Service

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#1544]

**Comment by lyiyu66** [comment]
Checked with commit 07818f34cdeec53579c6f3dbbd34d8f025f74dbd
Regression testing is passed on saas/lite versions.

**Comment by InaSong** [comment]
Confirmed in Singleton security code scanning alert page, all security scanning issues are fixed.
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/43361323/186059821-1df9db93-fcec-4f3e-a5cf-4ef378dcbf27.png">
