### ISSUE TITLE
[BUG][Ruby Client] Running rspec on single test file onclient_spec.rb fails

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1560]
**Describe the bug**
Running rspec on single test file ./spect/unit/onclient_spec.rb fails

**To Reproduce**
1. Go to client root
2. Run `rspec ./spect/unit/onclient_spec.rb`
3. See errors

**Expected behavior**
Tests should pass. The test file should be able to succeed independent of other test files. Otherwise, CI may fail if incorrect order of test files are run.

**Comment by Xiaochao8** [comment]
the command should be `rspec ./spec/unit/onclient_spec.rb  `
