### ISSUE TITLE
[BUG] [Ruby Client] File read does not support thread concurrency

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1575]
**Describe the bug**
File read for source bundle is currently inside a synchronized block. This means only one thread can access it at a time, affecting performance.

**To Reproduce**
1. Use the ruby client lib in a sample app.
2. Launch multiple(e.g. 1,000) threads that will load a source bundle at the same time. Use a bundle that has a large data set to observe performance.
3. Notice that the threads wait for their turn and so affecting performance.
4. Do the same for any offline bundle and see the same performance hit.

**Expected behavior**
Multiple threads should be able to read the source bundle at the same time.

**Comment by jessiejuachon** [comment]
@lyiyu66 , @InaSong

**Comment by lyiyu66** [comment]
Due to current design is changed and the related code is deleted, hence closing it.
