### ISSUE TITLE
[REQUIREMENT] [Ruby] Revisit design and class diagrams, then refactor code

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1576]
**Is your feature request related to a problem? Please describe.**

- [x] It is unclear what design patterns are used, if any, in the library. 
- [x] Some terminologies are inconsistent (e.g. "source" vs "default" vs "fallback")
- [x] Some code logic implementations are duplicated / complex.
- [x] Mark internal methods as private
- [x] Add source comparison
- [x] Only one same request(component-locale combination) is allowed at the same time
- [x] Config class
	-  It has many unnecessary code and needs to refractor.
	- Add necessary configuration items and remove uncessary configuration items.
- [x] Refractor cache module to use lock to make sure concurrency safe.
- [x] Refractor logger
- [x] Define new interfaces to make client easy-to-use.

**Describe the solution you'd like**
A clear and concise product design that may include class diagrams and and/or design patterns used.
Multiple small refactor-related PRs.

**Comment by lyiyu66** [comment]
Checked with commit 63145ec8b9f3d47d59ea3b623ce1a1cf21826b7e, no issue is introduced. And the new enhancements(source comparison, one same request, logger level&log file, new interfaces) have been verified in previous commits.
Hence closing.
