### ISSUE TITLE
[REQUIREMENT] [Ruby Client] Mixed mode

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1598]
**Is your feature request related to a problem? Please describe.**
When fetching an online bundle fails, use offline bundle if available.

**Describe the solution you'd like**
Implement Mixed Mode (falling back to offline bundles when VIP service bundle is not available). See L10n Fetch specifications

**Comment by lyiyu66** [comment]
Checked with build 0.7.0.36 with commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313, this feature has been tested and work well.
