### ISSUE TITLE
[BUG] [Ruby Client] Prevent multiple requests when translation bundle is not available yet.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#1604]
**Describe the bug**
When translation bundle is unavailable or when request for it fails, the client application keeps on sending the same request to VIP service (or trying to fetch from offline bundle).

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help you explain your issue

**Desktop (please complete the following information):**
 - Browser Name [e.g. chrome, safari]
 - Browser Version [e.g. 22]

**Additional context**

**Comment by lyiyu66** [comment]
With commit 63145ec8b9f3d47d59ea3b623ce1a1cf21826b7e, it won't send out request when translation bundle is not available in pervious request.
