### ISSUE TITLE
[BUG] [Java Service]Return 200 when requested product has invalid component in v2 product API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1606]
**Describe the bug**
Return 200 when requested product has invalid component in v2 product API.
GET
[/i18n/api/v2/translation/products/{productName}/versions/{version}](http://localhost:8091/i18n/api/doc/swagger-ui.html?urls.primaryName=v2#/operations/translation-product-api/getMultipleComponentsTranslationUsingGET_1)

**To Reproduce**
1. Go to 'GET [/i18n/api/v2/translation/products/{productName}/versions/{version}]' API.
2. Input below data: there is a component folder named with "big custom" in product VMwareVIP.
http://localhost:8091/i18n/api/v2/translation/products/VMwareVIP/versions/1.1.0?locales=en&pseudo=false
3. See error
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": {
    "productName": "VMwareVIP",
    "version": "1.1.0",
    "dataOrigin": "",
    "pseudo": false,
    "machineTranslation": false,
    "locales": [
      "en"
    ],
    "components": [
      "big custom",
      "custom",
      "custom100",
      "default"
    ],
    "bundles": [
      {
        "component": "big custom",
        "messages": {
          "Partner_Name": "Partner Name",
          "Dear_Custom": "Dear Custom"
        },
        "locale": "en"
      },
      {
        "component": "custom",
        "messages": {
          "Partner_Name": "Partner Name",
          "Dear_Custom": "Dear Custom"
        },
        "locale": "en"
      },
      {
        "component": "custom100",
        "messages": {
          "Partner_Name": "Partner Name",
          "Dear_Custom": "Dear Custom"
        },
        "locale": "en"
      },
      {
        "component": "default",
        "messages": {
          "Partner_Name": "Partner Name",
          "Verify_Translation": "Verify Translation"
        },
        "locale": "en"
      }
    ],
    "url": "",
    "id": 0
  }
}
```

**Expected behavior**
Return to 400 with incorrect component message.
```
{
  "code" : 400,
  "message" : "Incorrect components(only allows letter, number, comma, dot, underline, dashline)",
  "serverTime" : ""
}
```

**Comment by tigershi** [comment]
I have checked the all component name in singleton. All components have passed component validation

**Comment by lyiyu66** [comment]
It is reproduced on LITE also.

**Comment by lyiyu66** [comment]
Checked build with commit 45d7c2b4056fd41b9a477f7e383574f9e1df3381, the issue is fixed.
