### ISSUE TITLE
[BUG] [Java Service]The api response time of Java saas 0.6.0.207 is longer than Java saas 0.6.0.137

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1609]
**Describe the bug**
The api response time of Java saas 0.6.0.207 is longer than Java saas 0.6.0.137

**To Reproduce**
1. The old build of java service: singleton-manager-i18n-saas-0.6.0.137.jar
    The new build of java service: singleton-manager-i18n-saas-0.6.0.207.jar
   Test environment: 10.185.19.42 cup:1/2GHZ memory:967Mb
2. The test bundle : VMCUI 4.9Mb
    Test api: 
    regionlist: https://10.185.19.42:8090/i18n/api/v2/locale/regionList?supportedLanguageList=${v2getsupportedlanguagelist}
i18npattern: https://10.185.19.42:8090/i18n/api/v2/formatting/patterns/locales/${v2getPatternLocale}?scope=${v2getPatternScope}
componentlist: https://10.185.19.42:8090/i18n/api/v2/translation/products/${v2getComponentListProduct}/versions/${v2getComponentListVersion}/componentlist
LocaleList: https://10.185.19.42:8090/i18n/api/v2/translation/products/${v2getLocaleListProduct}/versions/${v2getLocaleListVersion}/localelist
componenttranslation: https://10.185.19.42:8090/i18n/api/v2/translation/products/${v2getComponentTranslationProduct}/versions/${v2getComponentTranslationVersion}/locales/${v2getComponentTranslationLocale}/components/${v2getComponentTranslationComponent}?pseudo=${v2getComponentTranslationPseudo}
alltranslation: https://10.185.19.42:8090/i18n/api/v2/translation/products/${v2getProductAllTranslationProduct}/versions/${v2getProductAllTranslationVersion}?pseudo=${v2getProductAllTranslationPseudo}

**Screenshots**
new build singleton-manager-i18n-saas-0.6.0.207.jar: 
![image](https://user-images.githubusercontent.com/64178605/158719404-70eca6dc-036f-4886-ae6b-9784700ad642.png)
old build singleton-manager-i18n-saas-0.6.0.137.jar:
![image](https://user-images.githubusercontent.com/64178605/158719342-cc48c67e-82f8-4bf4-ac06-dcb3b7d0cdfe.png)

**Comment by lyiyu66** [comment]
The latest behavior as below:
![image](https://user-images.githubusercontent.com/51813046/159822877-fdb91a5b-de67-4af8-b117-7f9c08c761ec.png)

**Comment by InaSong** [comment]
According to Yiyu's latest testing result, close this and we will track the follow up in new tasks.
