### ISSUE TITLE
[BUG] [L10n] write creation.json before translation bundle files

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1616]
**Describe the bug**
In Singleton Service, we have a file creation.json to store the information about translation operation, to make sure the notification information of translation update is correct, please update creation.json first.

**Actual Result**
The notification info is from previous operation of translation update, not the latest one due to creation.json is not update in time.
 
**Expected behavior**
File creation.json file can be updated before translation updated.

**Comment by tigershi** [comment]
we discussed the issue not any change for business flow. The PR: https://github.com/vmware/singleton/pull/1620
