### ISSUE TITLE
[BUG] [Java Service]Doesn't have validation for key in POST keyset API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1625]
**Describe the bug**
Doesn't have validation for key in POST keyset API.

**To Reproduce**
1. Go to API:
POST
 [/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys](http://localhost:8091/i18n/api/doc/swagger-ui.html?urls.primaryName=v2#/operations/translation-product-component-key-api/postSourcesUsingPOST)'
2. Input key with space/%/&... non-supported characters.
3. See the response:  Return to code=200 in response and accept such key

**Expected behavior**
For API consistent, key should have value validation, and return code=400 and message about what kind of character is supported.

**Comment**
Checked on the current product that is using POST keyset API, they already use some keys with special character, such as /, $....(maybe there are others that is not in our supported character list: letter, dot, comma, underline, dashline, pound)
If key in body field do the validation, it will fail to collect source when source keyset have above special characters as key name.

**Comment by tigershi** [comment]
the key and keys validation only allows ASCII char

**Comment by InaSong** [comment]
The key validation enablement has been confirmed with PO, which will resolve the blocker of product source collection.

**Comment by tigershi** [comment]
I tend to think that we can add some warning message when doing source collection stage ( in scanner or other source collection tools)

**Comment by lyiyu66** [comment]
@tigershi ,here mentions ASCII char, does it includes standard ASCII(0-128) and extended ASCII(129-255) chars?

**Comment by tigershi** [comment]
only includes standard ASCII(0-128)

**Comment by lyiyu66** [comment]
Commit: 93ffa26a7c0616ff7fee3eb25318342d1dc8975b
For the key with standard ASCII chars, it can collect successfully.
For the key with extended ASCII chars, it can't be collected and return to 400 with message.
