### ISSUE TITLE
[Requirement][Java Service] Provide detailed error messages if part of keys failed for source collection

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1626]
For Service POST API:
i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys

If 1 of 100 keys failed to be collected and processed by Service, the error message should be more detailed (include error key information), which would be better to client or users to find out the root cause.

Suggested error message: Incorrect source format ' %s' for key '%s' (only allows empty, STRING, MD, HTML, SVG)

- First %s means the value of source format that user assigned
- Second %s means the key of current string

**Comment by tigershi** [comment]
It will return the first error key name in error message. The following is the error message format: Incorrect '%s' sourceformat(only allows empty, MD, HTML, SVG).

**Comment by wangyi-e** [comment]
The following is the error message format: **Incorrect '%s' sourceformat(only allows empty, MD, HTML, SVG).**
The error message may not be very clear.
What does ‘%s’ stand for? The key or key's sourceFormat?
Is there any other reason for request failure besides sourceFormat not supported?
Can you give some concrete examples？

**Comment by InaSong** [comment]
Suggested error message: Incorrect source format ' %s' for key '%s' (only allows empty, MD, HTML, SVG)
