### ISSUE TITLE
[Requirement][Java Service] Error response will return if API request message is larger than 10M

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1637]
Return with failed result and provide error message once received 10M+ messages in source collection APIs.

**Comment by JiLiang888** [comment]
test OK  
suggest add unit in reponse message may be look better,i will take another issue 
![image](https://user-images.githubusercontent.com/82644009/180163729-8b4a3ce9-f91f-4434-8db8-8046a3e667d5.png)
