### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (springfox-swagger-ui)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1639]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- springfox-swagger-ui (2.9.2) --> 3.0.0

**Comment by tigershi** [comment]
Because the spring boot 2.5 can't support 3.0.0. We need to upgrade spring boot to 2.6+, if we want to upgrade swagger-ui to 3.0.0

**Comment by lyiyu66** [comment]
commit 93ffa26a7c0616ff7fee3eb25318342d1dc8975b
The regression testing is done and no related issue is found.

**Comment by nannany00** [comment]
Security check is pass.
