### ISSUE TITLE
[CI] [BUG] The master branch CI skip the CI task

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#1660]
**Describe the bug**
The detail please look at the PR
https://github.com/vmware/singleton/pull/1641

**Comment by junw-33455432** [comment]
You can find the CI triggered and all stages passed in "checks" tab: https://github.com/vmware/singleton/pull/1641/checks .
Usually CI stages shows in first page but for this PR, it shows in "checks" tab.
Let me check the view rule and update to you.

**Comment by junw-33455432** [comment]
For those PR only contains configure file change, please go to "Check" tab of the PR to find GitHub Actions execution status.
