### ISSUE TITLE
[BUG] Remove the deprecated API(Translation With Pattern API - POST) from swagger UI

### ISSUE THREAD

**Issue by linr211** [vmware/singleton#1687]
**Describe the bug**
There's a deprecated API(Translation With Pattern API - POST) on swagger UI, needs to remove it as it's useless.

**To Reproduce**
1. Go to 'swagger ui'
2. Click on 'Translation With Pattern API'

**Comment by wangyi-e** [comment]
Angular client is using this API (Translation With Pattern API - POST), and it is not recommended to delete it in the near future.

**Comment by lyiyu66** [comment]
Commit: 5f9c93ce435a14118373688d45c3f27d5b2d3f7a
The api has been removed from swagger-ui and this interface still is working via API url.
