### ISSUE TITLE
[BUG] [Ruby Client](translate&get_translations) When the request key or  request component is not in source bundle,  client should not ruturn translation

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1690]
**Describe the bug**
When the request key or  request component is not in source bundle,  client should not ruturn translation
This bug both occur in online and offline bundle

**To Reproduce**
1. The key "about.change" in service bundle and not in source bundle
2. Request translation: request1:Singleton.translate("about.change", 'about', 'de')
                                     request2:Singleton.get_translations("about", 'de')
**request1:client return de translation from service bundle**
**request2:client return bundle is contains key "about.change"**

1. The component "contact" in service bundle and not in source bundle
2. Request translation: Singleton.translate("contact.key1", 'contact', 'de')
**client return de translation from service bundle**

**Expected behavior**
Client should return error according to client workflow

**Comment by jessiejuachon** [comment]
This is a feature, not a bug.

**Comment by dleng-vmware** [comment]
This scenario isn't "no client-side source scenario"
the key "about.change" in component "about", and component "about" both in client source and server, but the key only in server.
such as client source has: about.key1 =value 1, about.key2 =value 2
             server en has: about.key1 =value 1, about.key2 =value 2, **about.change= en change**
             server de has: about.key1 =value 1, about.key2 =value 2, **about.change= de change**
request: Singleton.translate("about.change", 'about', 'de')
get value "de change",so it not compare source

**Comment by Xiaochao8** [comment]
After disscussion with our QEs, we agree not to fix this because returning translation won't introduce any problems.
