### ISSUE TITLE
[BUG] [Ruby Client]The translation response time of v0.7.0.36 has increased several times compares to v0.7.0.32.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1711]
**Describe the bug**
The translation response time of v0.7.0.36 has increased several times compares to v0.7.0.32.
Build info:
0.7.0.32: https://rubygems.org/gems/singleton-client-test/versions/0.7.0.32: commit d1ca65a5b051e82619b9fc81b9188119eb86b05a
0.7.0.36: https://rubygems.org/gems/singleton-client-test/versions/0.7.0.36: commit 09f7be8d62b86f6ae5c891a3c7d7e175059fa313

**To Reproduce**
1. Run the test.rb file for different size of bundle with offline mode.
2. Attaching the test.rb file.
3. See the result:
![image](https://user-images.githubusercontent.com/51813046/169429407-1f43e14c-90f2-493a-b610-05c106d198cf.png)

**Expected behavior**
The performance should be optimized.

**Comment by lyiyu66** [comment]
Add more info: when loading en translation (it means read the source from xx.yml file), it is also slow in v0.7.0.32. It will consume around 1.4s when component size is 7MB about 26789keys.

**Comment by Xiaochao8** [comment]
The fix has been reverted through #1724.

Now there are 2 options to this issue.

1. Support JSON format source files because reading JSON is much faster than reading YAML in Ruby.
2. Provide an interface to load translations, so users can initialize translations when application starts up.
