### ISSUE TITLE
[BUG] [Service] UT failed for Singleton Service build

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1715]
**Describe the bug**
When to compile Singleton Service Build with latest commit, 1 UT failed:
```
com.vmware.l10n.source.service.TestSyncI18nSourceService > test001sendSourceToI18n FAILED
    java.lang.IllegalArgumentException at TestSyncI18nSourceService.java:108
```

**Comment by tigershi** [comment]
I have done serial time in my computer. I guess it is an environmental problem and I suggest that you can use the command: ### **./gradlew clean build** have a try

**Comment by tigershi** [comment]
It have work well in new environment. It is a runtime environment issue.
