### ISSUE TITLE
[BUG] Reduce redundant commits when devops

### ISSUE THREAD

**Issue by sjiang-cb** [vmware/singleton#1717]
**Describe the bug**
There are redundant commits in JSClient 

**To Reproduce**
git log to checkt the log 

**Expected behavior**
One task should only commit once

**Screenshots**
![image](https://user-images.githubusercontent.com/67349945/170398793-77bed290-3c9e-441c-8e02-6aa0b6c089ea.png)

Carbon Cloud team would like to review JSClient before Integration, So have to clean redundant commits

**Comment by sjiang-cb** [comment]
When do one thing, it should use one commit , not frequently commit code , it will make Product team feel our code not seriously
![image](https://user-images.githubusercontent.com/67349945/170397830-d5bb67ff-29d6-45da-806d-2ed73e0014cc.png)

**Comment by junw-33455432** [comment]
To reduce the redundant commits, the branch has been reset to suggested commit and redundant commits have been merged to one commit. @sjiang-cb has confirmed that.
