### ISSUE TITLE
[BUG] [Ruby Client]When only translation_bundle is exist, client not compare message_en.json with message_latest.json.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#1718]
**Describe the bug**
When only translation_bundle is exist, client not compare message_en.json with message_latest.json.

**To Reproduce**
1. In translation_bundel, the key "about.notequal2" both exist in message_latest.json and message_en.json, but Their values are not equal
2. request translation: Sgtn.translate('about.notequal2', "about", 'de')
result: return  the de translation of key 'about.notequal2'

**Expected behavior**
It should compare message_latest.json and message_en.json, and return the value in message_latest.json

**Comment by jessiejuachon** [comment]
@dleng-vmware , what do you mean by "When only translation_bundle is exist" ?

**Comment by dleng-vmware** [comment]
@jessiejuachon Like this: in config.yaml,The vip_server and source_bundle are empty
![image](https://user-images.githubusercontent.com/64178605/171311944-08331a9d-8516-4cc9-a783-0a603dd33edd.png)

**Comment by dleng-vmware** [comment]
The bug fixing
