### ISSUE TITLE
[BUG] CI failure can't stop merge in Ruby client 

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1736]
**Describe the bug**
Even some steps of Ruby client CI fail, PRs can still be merged successfully.

**To Reproduce**
Submit a PR and make some steps of CI fail, the PR can still be merged successfully despte the failure.

**Comment by junw-33455432** [comment]
Relevant setting has been updated, now CI status check is a must have stage before PR's merge.
