### ISSUE TITLE
[DevOps] [Go Service] CI fails after upgrading Golang to 1.18 

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#1777]
CI fails after upgrading Golang to 1.18.
The failure message is:
`go: github.com/swaggo/swag@v1.8.3 requires
	golang.org/x/tools@v0.1.10: missing go.sum entry; to add it:
	go mod download golang.org/x/tools`
I ran this command locally but output was empty and nothing changed.

Please chec details in this PR: https://github.com/vmware/singleton/pull/1765

**Comment by junw-33455432** [comment]
Fixed, please refer to this PR: https://github.com/vmware/singleton/pull/1789
