### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (aws-java-sdk-s3)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1792]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- aws-java-sdk-s3(1.12.14) --> 1.12.261

**Comment by lyiyu66** [comment]
commit 93ffa26a7c0616ff7fee3eb25318342d1dc8975b
The regression testing is done and no related issue is found.

**Comment by nannany00** [comment]
Security check pass.
