### ISSUE TITLE
[BUG] [Java Service]Source parameter is query of POST API /i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys/{key} on swagger ui.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1800]
**Describe the bug**
commit: 5f9c93ce435a14118373688d45c3f27d5b2d3f7a
Source parameter is query of POST API /i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys/{key} in swagger ui.

**To Reproduce**
1. Go to 'POST API /i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys/{key}' in swagger-ui.
2. Check the content:
![image](https://user-images.githubusercontent.com/51813046/180735743-5643123a-b4ac-493b-8f1f-a53edcca5d5a.png)

**Expected behavior**
It is POST api, source should be body rather than query.

**Comment by tigershi** [comment]
It changed in PR: https://github.com/vmware/singleton/pull/1432

**Comment by lyiyu66** [comment]
The issue is fixed with commit 93ffa26a7c0616ff7fee3eb25318342d1dc8975b.
![image](https://user-images.githubusercontent.com/51813046/182275702-05ea749a-6d9d-4910-a92e-1b10ce5243c8.png)
