### ISSUE TITLE
[Go Service] Increase code coverage to 80%

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1802]

**Comment by junw-33455432** [comment]
I can see the unit test coverage is over 80% as expected in latest PR https://github.com/vmware/singleton/pull/2121 and the pass rate in the codecov configure has been set to 80%.

**Comment by lyiyu66** [comment]
Refer the comment https://github.com/vmware/singleton/issues/1802#issuecomment-1461140334, mark it as closed
