### ISSUE TITLE
[BUG][Java Service][V1]Validation of getting product's translation API is changed to take precedence from the component list to the locale list.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1808]
**Describe the bug**
commit:a7bf25f582fc5ffc06ea7cc4ad7bd217f8263839
Validation of getting product's translation API is changed to take precedence from the component list to the locale list.

**To Reproduce**
1. Go to 'V1 GET
[​/i18n​/api​/v1​/translation](https://g11n-vip-dev-1.eng.vmware.com:8090/i18n/api/doc/swagger-ui/index.html?urls.primaryName=v1#/translation-product-api/getProductTranslationUsingGET)' API.
2. Set a non-existing version like: `https://g11n-vip-dev-1.eng.vmware.com:8090/i18n/api/v1/translation?productName=Testing&version=90&locale=zh-hans`
3. See response:
```
{
  "response": {
    "code": 404,
    "message": "Failed to get locale list for Testing/90",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Expected behavior**
Should keep it as component list validation takes priority if no additional requirement/background.
In previous version(0.6.5.0), the response message is "Failed to get component list for Testing/90".

**Comment by tigershi** [comment]
This is not a bug, because fixed https://github.com/vmware/singleton/issues/1652 , run the the locale format first. So return the get locale list error message

**Comment by lyiyu66** [comment]
According to above comment, it is design change. Hence closing.
