### ISSUE TITLE
[BUG] [Java Servive] suggest response message can print details : use standard ASCII char instead of ASCII char

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1813]
**Describe the bug**
suggest response message can print details : use standard ASCII char instead of ASCII char

**To Reproduce**
1. use post api ,such as :
[(http://localhost:8091/i18n/api/v2/translation/products/test/versions/1.1.0/locales/en-US/components/0728post/keys/ddf%22%27%2C%3F%2F?collectSource=true)](http://localhost:8091/i18n/api/v2/translation/products/test/versions/1.1.0/locales/en-US/components/jie0728/keys?collectSource=true)
2. BODY : 
[
  {
    "commentForSource": "string",
    "key": "¼",
    "source": "string",
    "sourceFormat": "string"
  }
]

**Expected behavior**
{
  "code" : 400,
  "message" : "Incorrect key name '©' contains non-ASCII char(only allows standard ASCII char)",
  "serverTime" : ""
}

**Screenshots**
![image](https://user-images.githubusercontent.com/82644009/181475674-8d8cc345-7174-40ec-a516-119333b5b5e4.png)

commit 93ffa26a7c0616ff7fee3eb25318342d1dc8975b

**Comment by tigershi** [comment]
The issue is as same as https://github.com/vmware/singleton/issues/1810

**Comment by JiLiang888** [comment]
test ok ，same as #1810
