### ISSUE TITLE
[BUG][Java Service][V1]Failed to get translation when requested locale is zh-cn/en-us/de-ch via GET ​API /i18n​/api​/v1​/translation​/components.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1823]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/93ffa26a7c0616ff7fee3eb25318342d1dc8975b
[V1]Failed to get translation when requested locale is zh_cn/en-us/de-ch/en-001 via GET ​API /i18n​/api​/v1​/translation​/components.

**To Reproduce**
1. Go to 'GET ​API /i18n​/api​/v1​/translation​/components'
2. Request en-us locale's translation as below:
https://<ip>:8090/i18n/api/v1/translation/components?productName=VMwareVIP2018&version=1.1.0&components=default&locales=en-us
3. See error:
```
{
  "response": {
    "code": 404,
    "message": "Faild to get translation from data for VMwareVIP2018/1.1.0",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Expected behavior**
Should get en translation correctly.

**Comment by tigershi** [comment]
the issue is as same as https://github.com/vmware/singleton/issues/1815
