### ISSUE TITLE
[BUG][Java Service][V2]Failed to return the key name with comma(,) via GET keys API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1824]
**Describe the bug**
commit: 93ffa26a7c0616ff7fee3eb25318342d1dc8975b
Failed to return the key name with comma(,) via GET keys API.
Effected api: GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys]

**To Reproduce**
1. Go to 'GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys]' API.
2. Request a key name(example: "additional,Prop2") with comma:
https://<ip>:8090/i18n/api/v2/translation/products/Testing/versions/10.0.0/locales/zh-cn/components/default/keys?keys=additional%5C%2CProp2
3. See error:
```
{
  "response": {
    "code": 404,
    "message": "translation is not found",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Expected behavior**
It should return to key(additional,Prop2)'s translation: "字串2"
The default component's translation in bundles:
```
{
  "component" : "default",
  "locale" : "zh-Hans",
  "messages" : {
    "additional,Prop2" : "字串2",
    "additional/Prop3" : "字串3",
    "additional\\Prop1" : "字串1"
  }
}
```

**Comment by tigershi** [comment]
this is not a bug, The GET keys API can't support get translation that key contain comma(,)

**Comment by lyiyu66** [comment]
Closing it according to above comment.
