### ISSUE TITLE
[Java Service] Singleton Support JDK 17/18

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1836]
Singleton service need support JDK 17/18.

**Comment by tigershi** [comment]
I have tested that the the singleton, lite-singleton, l10n manger, l10n manger can run successfully on OPEN jdk17&18 in Window OS.

**Comment by tigershi** [comment]
need add the following JVM variable when starting:
java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-0.1.0.jar

**Comment by tigershi** [comment]
https://confluence.eng.vmware.com/display/GQ/Singleton+jdk+support

**Comment by tigershi** [comment]
singleton	lite-singleton	l10n-manager

support	Dependency Startup Options	support	Dependency Startup Options	support 	Dependency Startup Options
jdk1.8	yes	no	yes	no	yes	no
jdk9	yes	no	yes	no	yes	no
jdk11	yes	no	yes	no	yes	no
jdk17	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar
jdk18	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar

**Comment by tigershi** [comment]
``<html>
<body>
<div class="page-metadata" style="margin: -15px 0px 20px; padding: 0px; font-size: 12px; color: rgb(94, 108, 132); line-height: 1.5; font-weight: 300; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><ul style="margin: 0px; overflow: hidden; padding: 0px; list-style-type: none; line-height: 16px; display: inline-block; vertical-align: bottom;"><li class="page-metadata-modification-info" style="list-style: none; float: left; padding: 0px; margin: 0px; line-height: 1.5;">由<span class="author"><span> </span><a href="https://confluence.eng.vmware.com/display/~shihu" class="url fn confluence-userlink userlink-0" data-username="shihu" title="" data-user-hover-bound="true" style="color: rgb(94, 108, 132); text-decoration: none; font-size: 12px; line-height: 1.5; font-weight: 300;">Hu Shi (c)</a></span>创建, 最后修改于<a class="last-modified" title="查看变更" href="https://confluence.eng.vmware.com/pages/diffpagesbyversion.action?pageId=1496022504&amp;selectedPageVersions=2&amp;selectedPageVersions=3" style="color: rgb(94, 108, 132); text-decoration: none; font-size: 12px; line-height: 1.5; font-weight: 300;">九月 20, 2022</a></li></ul><ul class="cw-bylines" style="margin: 0px; display: inline-block; font-size: 12px; color: rgb(112, 112, 112); list-style-type: none; overflow: hidden; padding: 0px; line-height: 16px; vertical-align: top;"><li class="cw-byline-item" style="display: inline-block; list-style: none; padding: 0px 5px 0px 0px; margin: 0px; line-height: 1.5; float: left;"><div id="cw-approval-byline" class="cw-approval-byline" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: -5px !important; padding: 0px;"></div></li><li class="cw-byline-item" style="display: inline-block; list-style: none; padding: 0px 5px 0px 0px; margin: 0px; line-height: 1.5; float: left;"><div id="cw-state-byline" class="cw-state-byline" style="margin: 0px; padding: 0px; color: rgb(204, 204, 204);"></div></li><li class="cw-byline-item" style="display: inline-block; list-style: none; padding: 0px 5px 0px 0px; margin: 0px; line-height: 1.5; float: left;"><div id="cw-tasks-byline" class="cw-tasks-byline" style="margin: 0px; padding: 0px;"></div></li><li class="cw-byline-item" style="display: inline-block; list-style: none; padding: 0px 5px 0px 0px; margin: 0px; line-height: 1.5; float: left;"><div id="cw-state-alternate" class="cw-state-alternate" style="margin: 0px; padding: 0px;"></div></li></ul></div><a href="https://confluence.eng.vmware.com/display/GQ/Singleton+jdk+support#page-metadata-start" class="assistive" style="color: rgb(0, 82, 204); text-decoration: none; border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; margin: -1px; overflow: hidden; padding: 0px; position: absolute; width: 1px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">转至元数据起始</a><div id="page-metadata-end" class="assistive" style="margin: -1px; padding: 0px; border: 0px; clip: rect(0px, 0px, 0px, 0px); height: 1px; overflow: hidden; position: absolute; width: 1px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div id="rioja-page-message" style="margin: 0px 0px 20px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div><div id="main-content" class="wiki-content" style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="table-wrap" style="margin: 0px; padding: 0px; overflow-x: auto;">

  | singleton | lite-singleton | l10n-manager
-- | -- | -- | --
  | support | Dependency Startup Options | support | Dependency Startup Options | support | Dependency Startup Options
jdk1.8 | yes | no | yes | no | yes | no
jdk9 | yes | no | yes | no | yes | no
jdk11 | yes | no | yes | no | yes | no
jdk17 | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar
jdk18 | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar

</div></div>
</body>
</html>由 [Hu Shi (c)](https://confluence.eng.vmware.com/display/~shihu)创建, 最后修改于[九月 20, 2022](https://confluence.eng.vmware.com/pages/diffpagesbyversion.action?pageId=1496022504&selectedPageVersions=2&selectedPageVersions=3)
[转至元数据起始](https://confluence.eng.vmware.com/display/GQ/Singleton+jdk+support#page-metadata-start)

singleton	lite-singleton	l10n-manager

support	Dependency Startup Options	support	Dependency Startup Options	support 	Dependency Startup Options
jdk1.8	yes	no	yes	no	yes	no
jdk9	yes	no	yes	no	yes	no
jdk11	yes	no	yes	no	yes	no
jdk17	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar
jdk18	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar	yes	java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar

**Comment by tigershi** [comment]
`
<html>
<body>
<p style="margin: 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>

  | singleton | lite-singleton | l10n-manager
-- | -- | -- | --
  | support | Dependency Startup Options | support | Dependency Startup Options | support | Dependency Startup Options
jdk1.8 | yes | no | yes | no | yes | no
jdk9 | yes | no | yes | no | yes | no
jdk11 | yes | no | yes | no | yes | no
jdk17 | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar
jdk18 | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar lite-singleton-xxx.jar | yes | java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar l10n-manager-xxx.jar

<p style="margin: 10px 0px 0px; padding: 0px; color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"> </p>
</body>
</html>

`
