### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (neko-htmlunit)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1845]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- neko-htmlunit  (2.24) --> 2.61.0 or 2.27

**Comment by tigershi** [comment]
I have upgraded to 2.63.0

**Comment by nannany00** [comment]
Security check pass.

**Comment by lyiyu66** [comment]
Checked with commit 07818f34cdeec53579c6f3dbbd34d8f025f74dbd
Regression testing is pass on saas/lite versions.
