### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (snakeyaml )

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1868]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- snakeyaml (1.29) --> 1.31

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
Commit: b5e27554d53a516e40248822756bf4d454454750
Regression testing is done and no issue is introduced.
