### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (httpcomponents-client)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1870]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- httpcomponents-client (5.1.3) --> 5.2

**Comment by tigershi** [comment]
I found the latest httpcomponents-client version is 4.5.13. And I also found the latest httpcomponents-client5 is 5.2.bate1.

**Comment by InaSong** [comment]
Discussed with team: currently we will keep httpcomponents-client with 4.5.13. Upgrade httpcomponents-client5 to latest stable version.

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
Commit: b5e27554d53a516e40248822756bf4d454454750
Regression testing is done and no issue is introduced.
