### ISSUE TITLE
[REQUIREMENT][GoService] Add health-check API

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1875]
**Is your feature request related to a problem? Please describe.**
In Singleton Service, add a Health-check API to help Service status: {host}/actuator/health

**Describe the solution you'd like**
To add a health check API same with Java Service, the path is like
```
{host}/actuator/health
```

**Comment by lyiyu66** [comment]
Checked with commit 8348aa31d4234c63de942b8c728164f8df4e286a, the behavior as below:
<html>
<body>


 
--

Service is running | return: {"status":"UP"} |  
Service is down | return:the site can't be reached |  


</body>
</html>
