### ISSUE TITLE
[BUG] [Go servive]No validation for illegal pattern character(eg. asdff) in formatting-api.

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1891]
**Describe the bug**
 request invalid pattern such as asdff , did vertify it for formatting-api

**To Reproduce**

1. Go to  formatting-api
2. request such as : http://localhost:9011/i18n/api/v2/formatting/date/localizedDate?locale=en&longDate=1472728030290&pattern=asdf

**Expected behavior**
{
  "response": {
    "code": 400,
    "message": "Illegal pattern character 'f' in \"asdf\"",
    "serverTime": ""
  }

**Screenshots**
![image](https://user-images.githubusercontent.com/82644009/191398796-5bef7cb2-aa61-4214-80dd-57dd115bb015.png)

commit 8348aa31d4234c63de942b8c728164f8df4e286a

**Comment by Xiaochao8** [comment]
This message is from 3rd party and can't be changed by ourselves. If the format string is correct, there won't be error.
No plan to fix.
