### ISSUE TITLE
[BUG] [Go service]Error message is not friendly when pseudo/checkTranslationStatus is not a boolean value.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1904]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/8348aa31d4234c63de942b8c728164f8df4e286a
Error message is not friendly when pseudo/checkTranslationStatus is not a boolean value.

**To Reproduce**
1. Go to the api with pseudo or checkTranslationStatus parameter. 
Example: GET
[/translation/products/{productName}/versions/{version}](http://localhost:9091/i18n/api/v2/swagger/index.html#/translation-product-api/get_translation_products__productName__versions__version_)
2. Input pseudo value as "truE": 
http://localhost:9091/i18n/api/v2/translation/products/VMwareVIP2018/versions/1.0?locales=en&components=default&pseudo=truE
3. See error:
```
{
    "response": {
        "code": 400,
        "message": "strconv.ParseBool: parsing \"truE\": invalid syntax"
    }
}
```

**Expected behavior**
```
{
    "code": 400,
    "message": "Incorrect pseudo(only allows true/TRUE, false/FALSE)"
}
```

**Additional context**
Same behavior about checkTranslationStatus parameter.

**Comment by Xiaochao8** [comment]
This messge is from 3rd party and can't be changed by ourselves. So don't plan to fix it.
