### ISSUE TITLE
[BUG] [Go service][v1&v2]Product api([translation-product-api]) returns to 200 if the included component name is invalid.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1910]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/7aeb07348a137caaef30f7c86ebece81207e0e38
[v1&v2]Product api([translation-product-api]) returns to 200 if the included component name is invalid.

**To Reproduce**
1. Take one of v2 product api as example: VMwareVIP/1.1.0 has a invalid component named with "big custom"
http://<ip:port>/i18n/api/v2/translation/products/VMwareVIP/versions/1.1.0?pseudo=false
2. See response:
![image](https://user-images.githubusercontent.com/51813046/194792425-406a7865-a869-4d39-a725-d59fd47e86e1.png)

**Expected behavior**
Return to 400 since the requested product/version has component with invalid name.

**Comment by Xiaochao8** [comment]
This component name isn't an input argument, server doesn't the data from storage. The data is put by user and server treats it as valid by default.

**Comment by Xiaochao8** [comment]
> Current behavior is different with Java Service.

It isn't  a problem because all the component names are valid.

**Comment by Xiaochao8** [comment]
Plan to not fix.

**Comment by lyiyu66** [comment]
According to above comment, closing it.
