### ISSUE TITLE
[BUG] [Go service][v1&v2]Product allow list doesn't work on PUT APIs. 

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1915]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/7aeb07348a137caaef30f7c86ebece81207e0e38
Product allow list doesn't work on v1&v2 PUT APIs. 

**To Reproduce**
Take v2 put api as example:
1. Set AllowList: true and go to translation-sync-api:
http://<ip:port>/i18n/api/v2/translation/products/newproduct/versions/21
2. Set below valid data as body:
`{"data": {"productName": "newproduct","pseudo": true,"translation":[{"component": "Test.ABC_abc-123","locale": "es-419","messages": {"Device.Driver.Notes": "Las Notas Terceras"}}],"version": "1.0"},"requester": "GRM"}`
3. See the response:
```
{
    "response": {
        "code": 200,
        "message": "OK"
    }
}
```

**Expected behavior**
Return to 400 due to newproduct is not in product allow list.
```
{
    "response": {
        "code": 400,
        "message": "Product 'nothisproduct' doesn't exist"
    }
}
```

**Comment by Xiaochao8** [comment]
Can't reproduce in my local env.

`curl -X 'PUT' \
  'http://localhost:8091/i18n/api/v2/translation/products/newproduct/versions/21' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "data": {
        "productName": "newproduct",
        "pseudo": true,
        "translation": [
            {
                "component": "Test.ABC_abc-123",
                "locale": "es-419",
                "messages": {
                    "Device.Driver.Notes": "Las Notas Terceras"
                }
            }
        ],
        "version": "1.0"
    },
    "requester": "GRM"
}'


{
  "response": {
    "code": 400,
    "message": "Product 'newproduct' doesn't exist"
  }
}`

**Comment by lyiyu66** [comment]
Close it as user error.
