### ISSUE TITLE
[BUG] [Java Service]Return 200 with empty data when there is no component in requesting product/version on localelist API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1919]
**Describe the bug**
commit: c6dac6545fa76d51cd1e5d53342855140647d551
Return 200 with empty data when there is no component in requesting product/version on localelist API.

**To Reproduce**
1. Go to 'GET
 [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/localelist]'
2. Request a product&version: no data under product/version folder.
3. Check the response:
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": {
    "locales": [],
    "version": "2.0.0",
    "productName": "SingleVersionNoData"
  }
}
```

**Expected behavior**
Should return 404 and null data.
```
{
  "response": {
    "code": 404,
    "message": "Failed to get locale list for SingleVersionNoData/2.0.0",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Comment by tigershi** [comment]
Not bug
