### ISSUE TITLE
[Security][Java Client] Please upgrade dependency libraries to latest version (jackson-databind)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1921]
In Singleton Java library, below dependency library is out of date, please upgrade it to latest version:

- jackson-databind (2.12.6.1)

**Comment by huihuiw01** [comment]
Java client doesn't depend on this lib directly, its' dependency i18n-pattern-core depends on this lib, so change need be done in g11n-cldr-pattern branch.

**Comment by lyiyu66** [comment]
The regression test is done with commit 1e28f1b5a30885d258b4614928bb99dc11be19a4.

**Comment by nannany00** [comment]
Security check is pass.
