### ISSUE TITLE
[Security][CLDR-Pattern] Please upgrade dependency libraries to latest version (jackson-databind)

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1925]
In Singleton Java library, below dependency library is out of date, please upgrade it to latest version:

jackson-databind (2.12.6.1)

**Comment by lyiyu66** [comment]
Regression testing is done on commit dd99e54752f73e741e23ff3316b1dbb675bce80e, no issue is found.

**Comment by lyiyu66** [comment]
Regression testing on commit 766c64815b9f323a2f1ac093d05ab437e4d18200 is passed.
