### ISSUE TITLE
[BUG][Java Service][S3]Return 200 with empty data when there is no component in requesting product/version on componentlist API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1926]
**Describe the bug**
commit: 5c86ed05f4c394a47afe25e7fc0501cdfa8f0bc8
Return 200 with empty data when there is no component in requesting product/version on componentlist API.
Reproducible on v1 and v2 componentlist APIs.
GET [​/l10n​/api​/v1​/bundles​/components](http://10.186.206.156:8091/i18n/api/doc/swagger-ui/index.html?urls.primaryName=v1#/translation-product-api/getComponentNameListUsingGET)
GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/componentlist](http://10.186.206.156:8091/i18n/api/doc/swagger-ui/index.html?urls.primaryName=v2#/translation-product-api/getComponentNameListUsingGET_1)

**To Reproduce**
1. Go to 'GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/componentlist]'
2. Request a product&version: no data under product/version folder.
3. See response
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": {
    "components": [
      ""
    ],
    "version": "2.0.0",
    "productName": "SingleVersionNoData"
  }
}
```

**Expected behavior**
Should return 404 and null data.
```
{
  "response": {
    "code": 404,
    "message": "Failed to get component list for SingleVersionNoData/2.0.0",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Comment by tigershi** [comment]
not bug
