### ISSUE TITLE
[Security][Java Client][CLDR-Pattern] Please upgrade dependency libraries to latest version (jackson-databind)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1945]
Please help to upgrade below library to latest version:
- jackson-databind (2.12.6.1)

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
Using commit 1e28f1b5a30885d258b4614928bb99dc11be19a4 to check the L2 feature(cldr relative function), regression is passed.
