### ISSUE TITLE
[BUG] [java service] source should be collected successfully when csp token setting true,details below

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#1952]
**Describe the bug**
[BUG] [java service] source should be collected successfully when csp token setting true,details below

**To Reproduce**

1. setting config file to enable/disable csp token
2. call i18n server api  /  call L10N server api
3. See result:
![image](https://user-images.githubusercontent.com/82644009/203244416-23795125-3c83-4cfe-a741-0f1ffcb6fd2e.png)

commit b4558452930dd64cdcce8c81f5d7a2193e2a08c8

**Comment by JiLiang888** [comment]
test OK ， except detail testcase ：
i18n on L10n off  : L10n servier without header call pai    --->  should l10n source collected successfully  ,  but  i18n l10n both source collected successfully
      
i18n off L10n on  : i18n servier without header call pai    --->  should i18n source collected successfully  ,  but  i18n l10n both source collected successfully

**Comment by tigershi** [comment]
singleton request  l10n and l10n request singleton don't have csp token validation.

**Comment by JiLiang888** [comment]
build.number.buildnumber=71e9aeda328a2ac08479df7d9b8f77acb9a8b352
