### ISSUE TITLE
[BUG][Singleton service]Fall back to 9.6 when requesting nonexistent version(9.6.2)'s translation, even though there has 9.6.1.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#197]
**Describe the bug**
Majior.Minor.Patch kind version can't fall back to previous same kind version if there is Majior.Minor kind version.
Example: there are versions 9.6, 9.6.1, now request the translation of version 9.6.2, it falls back to 9.6.

**To Reproduce**
1. Translation bundle are existed for version 9.6 and 9.6.1, no 9.6.2 translation.
2. Request the translation of version 9.6.2.

**Expected behavior**
Translation version should fall back to 9.6.1 when requesting 9.6.2.

**Comment by linr211** [comment]
not reproduced in my dev environment, please double check.

**Comment by lyiyu66** [comment]
It is not fixed with latest code, please have a check again.

**Comment by lyiyu66** [comment]
Checked with latest build 445, it is fixed. Hence closing.
![2019-10-22-fixed](https://user-images.githubusercontent.com/51813046/67266385-b819de00-f4e2-11e9-9bc7-9ee797bb7aaa.jpg)
