### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (snakeyaml)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#1974]
In Singleton Service, below dependency library is out of date, please upgrade it to latest version:

- snakeyaml (1.32)

**Comment by lyiyu66** [comment]
The regression testing is done with commit 6c94943e3a3af006107ba419256bbced5bd10fea, no issue is found.

**Comment by nannany00** [comment]
Security check is passed
