### ISSUE TITLE
[BUG] [CLDR Pattern]There are some missing files and incorrect location in generated cldr pattern.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#1975]
**Describe the bug**
commit: 3a489f56bb72459b34f5fe5d197b83f6e9965eb8
There are some missing files and incorrect location in generated cldr pattern.

**To Reproduce**
1. Generate the cldr pattern package and extract it.
2. Check the extracted file in step 1.
3. Some files are missed and one file are in incorrect directory as below screenshot:
Issue is reproducible on left side, the right side pane is correct and expected:
![image](https://user-images.githubusercontent.com/51813046/204442985-51f8d1c4-a931-421e-83a5-888e5b06f282.png)

**Expected behavior**
All files are there and in correct directory.

**Comment by huihuiw01** [comment]
The file 'parse.json' is not in incorrect directory, it's structure just be reorganized.

**Comment by lyiyu66** [comment]
The issue is fixed with commit 766c64815b9f323a2f1ac093d05ab437e4d18200 and service smoke testing with relative cldr jar package is passed.
