### ISSUE TITLE
[BUG] [Java Service] Change the config for log4j2 to limit log size

### ISSUE THREAD

**Issue by huihuiw01** [vmware/singleton#1988]
**Describe the bug**
Bug is reported by VMware internal product which mentioned Singleton service log directory could get larger over a time and take much disk space. Which is critical and could cause cluster instability and crashes.

Currently the config for single log file size is 64MB, and the max amount is 100, which means the max size of log folder is over 6GB. 

**To Reproduce**

**Expected behavior**
Limit total size of used disk for log directory. It implies limit size of files and number of file under log directory. Customer's expectation is it'll be less then 0.5 GB or even less.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by JiLiang888** [comment]
saas test ok;
lite  test ok;
L10n test failed, can't generated log file
