### ISSUE TITLE
[Doc] Update doc on website to guide users how to use self defined log config file when start Singleton service

### ISSUE THREAD

**Issue by huihuiw01** [vmware/singleton#1989]
**Describe the bug**
We provide a default log config file inside Singleton service package, if customer think it's not appropriate for them, they should be able to specify their own log config file. We need provide guide to let them know how to use their self defined log config file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 

**Additional context**

**Comment by tigershi** [comment]
https://confluence.eng.vmware.com/display/GQ/How+to+use+custom+log+configuration+file+in+Singleton+service

**Comment by tigershi** [comment]
I have updated doc in site: https://vmware.github.io/singleton/docs/overview/singleton-service/singleton-service-custom-log/

**Comment by lyiyu66** [comment]
The info can be shown successfully on web site. Hence closing.
