### ISSUE TITLE
[Requirement][Java Service] Upgrade Service Code to JDK 11

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#1994]
Update JRE (to 11.0.16, 8u341, 7u351) in the FIRST upcoming maintenance and major/minor releases of your product prior to GA. If JRE is out of date it will be flagged by vulnerability scanners, leading to customer complaints.

**Comment by tigershi** [comment]
I have written the investigation doc: https://confluence.eng.vmware.com/display/GQ/Singleton+upgrade+JDK+investigation

**Comment by lyiyu66** [comment]
The testing is done and result is attached as below table. The failed scenarios is tracked with the 3 opening bugs.
![image](https://user-images.githubusercontent.com/51813046/225352141-543e74a1-d81e-4186-bf0c-8f7604f6c187.png)
