### ISSUE TITLE
[Service] Get the latest CLDR pattern package when generate build

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2000]
Singleton provides a CLDR pattern package for formatting to Singleton Service Build. 
Please change the gradle setting to fetch the latest version of CLDR by default when generate Singleton Service Build.

**Comment by lyiyu66** [comment]
commit 9fc9657237fe2f8adbcd66ad1db19839200da38c:
it fetches singleton-i18n-patterns-core-0.5.12.jar as internal jar package, and its regression testing is passed.
