### ISSUE TITLE
[REQUIREMENT][CLDR-Pattern] Enable CLDR Smoke Test

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#2002]
**Is your feature request related to a problem? Please describe.**
Configure CLDR CI process to enable smoke tests

**Describe the solution you'd like**
Please refer to the completed task that Yiyu merged: https://github.com/vmware/singleton/issues/1958

The CI process is blocking the PR: 
https://github.com/vmware/singleton/pull/1997

**Comment by junw-33455432** [comment]
Hi @lyiyu66 , the test script for cldr pattern seems throws a exception during CI, could you take a look? Thanks.

**Comment by lyiyu66** [comment]
@junw-33455432 , looks like one jar has been copied to incorrect directory in your PR. I have left comment to the PR, please have a check.
