### ISSUE TITLE
[Service][L10n] Add customize request header item to log

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2008]
Sometimes, we need some information from other team in Request Header to follow-up the API request process, this is added in I18N manager, now, it's also needed in Singleton l10n Manager.

**Comment by JiLiang888** [comment]
pass

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/82644009/221763536-0323b794-3a1e-498d-9d97-512aaf0d45bd.png">
