### ISSUE TITLE
[BUG] [java service] without any validation when appid / token is error for vipservice authority

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2012]
**Describe the bug**
without any validation when appid / token is error for vipservice authority
**To Reproduce**
1. in application-bundle.properties:
#authority config
vipservice.authority.enable=true
2. Get token and appid 
3.request api ,input correct appID TOKEN

**Expected behavior**
/response/code=401;message=The authentication fails, please validate the token!

commit 19f0cf6e7afac2e6aa0ebb311ecb577ebef46f70

**Comment by tigershi** [comment]
it"s not a bug, please configure the public key and private key and following configuration
#authority config
vipservice.authority.enable=false
#the time unit is minute
vipservice.authority.token.expiretime=525600
#the jwt secret
vipservice.authority.jwt.secret=#
#ldap server url
vipservice.authority.ldap.server.url=###
#ldap domain
vipservice.authority.ldap.tdomain=#######
#ldap searchbase
vipservice.authority.ldap.searchbase=###

**Comment by JiLiang888** [comment]
pass
<img width="1334" alt="image" src="https://user-images.githubusercontent.com/82644009/220063062-46b62a9f-5325-459b-8a43-71ff36274c42.png">
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/82644009/220063188-b294ea97-fad1-4d9a-9d8a-8b40d7a79d8c.png">
