### ISSUE TITLE
[BUG] [java service] cache didn't expired if time over expiry time

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2016]
**Describe the bug**
cache didn't expired if time over expiry time

**To Reproduce**
1. in ehcache3.xml ,setting below :
<img width="574" alt="image" src="https://user-images.githubusercontent.com/82644009/209309473-e00db791-4edd-4841-9d9c-225851e1a397.png">

2. call api : http://localhost:8091/i18n/api/v2/locale/regionList?supportedLanguageList=ja  ---> get data from cache
3. after 1 hour , call api again --> get data from cache

**Expected behavior**
cache regions is null, get data from file

**Screenshots**

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/82644009/209309091-6f35e426-3485-4cc0-9e52-4fad3ec4b34b.png">

**Comment by tigershi** [comment]
this is not a bug, this is ehcache3 expire strategy

**Comment by tigershi** [comment]
we use the <ttl unit="hours">24</ttl>, please use the <ttl unit="seconds">200</ttl> configuration item to do test. I found that used the <tti unit="hours">24</tti> in description

**Comment by JiLiang888** [comment]
pass ;
use minutes unit to test
tti test pass
ttl test pass
