### ISSUE TITLE
[Service] [CLDR] extract more data for dates pattern from CLDR

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2037]
In Singleton , to support "B" pattern in each Singleton Client lib, Singleton Service needs to provide more data that extract from CLDR like
```
"dayPeriods": {
              "format": {
                "abbreviated": {
                  "midnight": "midnight",
                  "am": "AM",
                  "am-alt-variant": "am",
                  "noon": "noon",
                  "pm": "PM",
                  "pm-alt-variant": "pm",
                  "morning1": "in the morning",
                  "afternoon1": "in the afternoon",
                  "evening1": "in the evening",
                  "night1": "at night"
                },
......
```
References: 
CLDR data: https://github.com/unicode-cldr/cldr-dates-full/blob/master/main/en/ca-gregorian.json

**Comment by lyiyu66** [comment]
The testing is passed, pls see the result as below:

![image](https://user-images.githubusercontent.com/51813046/230247306-ca09475a-beb9-4ae4-882d-94cff582ff53.png)
