### ISSUE TITLE
[BUG] [Singleton Service]Fall back to previous version(7.x.x) but not the existing 8.0 when requesting nonexistent 8.0.0.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#205]
**Describe the bug**
Fall back to previous version(7.x.x) but not the existing 8.0 when requesting nonexistent 8.0.0.
Same behavior when requesting 6.0, it falls back to 5.x.x even though there has 6.0.0.

**To Reproduce**
1. There are the translation bundles of 8.0, 7.9.8, 6.0.0 and 5.9.8.
2. Request the translation of 8.0.0 or 6.0 (when user does not clearly remember the version number).

**Expected behavior**
Should fall back to the closest previous version if the difference of the requested and existing versions is the number of digit is different and value is 0. 
Example:
Request 8.0.0/8 -> 8.0
Request 6.0/6 -> 6.0.0
Request 5.6.0 -> 5.6
Request 7.2 -> 7.2.0

**Comment by linr211** [comment]
not reproduced in my dev environment. Could you double confirm it?
