### ISSUE TITLE
[REQUIREMENT][Go Client] Add "source locale" in Configuration as 2nd Priority Fallback Locale

### ISSUE THREAD

**Issue by InaSong** [vmware/singleton#2051]
**Is your feature request related to a problem? Please describe.**
Not support yet.

**Describe the solution you'd like**
Add "source locale" in configuration as the language of source, the 2nd priority fallback locale

**Comment by dleng-vmware** [comment]
Test pass in commit:1da43a857ed7ef63b7ea40c5c154446c91ca2232
