### ISSUE TITLE
[BUG][Go Client]Doesn't include the locales of localbundle as supported locales in mixed mode.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2064]
**Describe the bug**
commit: a9e43772bc294c4da6e3bf49212012ea512a78ca
Doesn't include the locales in localbundle of requested product/version as supported locales in mixed mode.
Translation interfaces: localelist interface.

**To Reproduce**
1. Config it as mixed mode(online+offline).
2. One locale only exists in localBundle, it doesn't in service. Example: messages_de.json exists in service, messages_de-CH.json exists in localBundle only.
3. Request locale list interface: `localelist1, err1 := translation.GetLocaleList("GoClientTest2", "1.0")`
4. See result: it return to the locales of requested product/version in online bundle

**Expected behavior**
It should return to the locales of requested product/version in online and offline bundles: the locales under product/version directory in online and offline bundles

**Comment by dleng-vmware** [comment]
the GetLocaleList will get all locales of locale bundles, whether or not the locale is currently supported by the requested product

**Comment by dleng-vmware** [comment]
the bug is fixed
