### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (spring-web)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2071]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:
- spring-web (5.3.21)

**Comment by lyiyu66** [comment]
Regression test is done on commit 71e9aeda328a2ac08479df7d9b8f77acb9a8b352, no issue is found by version upgrade.

**Comment by nannany00** [comment]
In scan result, it suggests to upgrade to 6.x.x, due to there will be much effort on it, and current version is latest one on 5.x.x, will close it first.
