### ISSUE TITLE
[BUG] [java service]Store encoded source in messages_latest.json when sourceFormat includes "base64" in POST a source API & Post a set of sources API. 

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2075]
**Describe the bug**
Get encoded source when sourceFormat includes "base64" in POST a source API & Post a set of sources API. 

**To Reproduce**
1. Go to http://10.186.206.156:8091/i18n/api/v2/translation/products/ABC/versions/1.2.0/locales/en/components/sss/keys/aaa?sourceFormat=base64%2Cstring&collectSource=true
2. Input "base64,string" as sourceFormat and valid data to other fields.

**Expected behavior**
in18n service collected source is decoded

https://build-artifactory.eng.vmware.com/ui/repos/tree/General/vip-gradle-local/singleton/test/singleton-manager-i18n-saas/0.6.10.15/singleton-manager-i18n-saas-0.6.10.17.jar

https://build-artifactory.eng.vmware.com/ui/repos/tree/General/vip-gradle-local/singleton/test/singleton-manager-l10n/0.6.10.2/singleton-manager-l10n-0.6.10.2.jar

**Comment by JiLiang888** [comment]
**below picture api  test not ok 
<img width="1494" alt="image" src**="https://user-images.githubusercontent.com/82644009/220065821-f22cdd75-c468-4941-a816-62378b325d1f.png">
https://build-artifactory.eng.vmware.com/ui/repos/tree/General/vip-gradle-local/singleton/test/singleton-manager-l10n/0.6.11.1/singleton-manager-l10n-0.6.11.1.jar

**Comment by tigershi** [comment]
The source API not support base64 function. only the translation-collect-key-api group APIs have base64 feature

**Comment by JiLiang888** [comment]
thank you , and test ok;
