### ISSUE TITLE
[BUG][Java service]Return to 200 when component name is invalid(includes space) in product based api.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2077]
**Describe the bug**
commit: 91854a0d419f91a887149cb26c5cbf6927136459
Return to 200 when component name is invalid(includes space) in product based api.

**To Reproduce**
1. Go to 'GET
[​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}]' API.
2. Input a product and version which its component with invalid name(name with space), just like named with "component 1".
3. See the response:
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": {
    "productName": "vmware2018",
    "version": "1.1.0",
    "dataOrigin": "",
    "pseudo": false,
    "machineTranslation": false,
    "locales": [
      "en",
      "ja",
      "zh-Hans"
    ],
    "components": [
      "big custom",
      "custom",
      "custom100",
      "default"
    ],
    "bundles": [
      {
        "component": "big custom",
        "messages": {
          "Dear_Custom": "Dear Custom",
          "Partner_Name": "Partner Name"
        },
        "locale": "en"
      },
      {
        "component": "big custom",
        "messages": {
          "Dear_Custom": "親愛なるお客様",
          "Partner_Name": "パートナー名"
        },
        "locale": "ja"
      },
      {
        "component": "big custom",
        "messages": {
          "Dear_Custom": "尊敬的客户",
          "Partner_Name": "合作伙伴名称"
        },
        "locale": "zh-Hans"
      },
      ...
}
```

**Expected behavior**
Should return to 400 since there is invalid component.

**Comment by tigershi** [comment]
Because of the it spend more resource validate the component after get componentlist from local disk or s3. To improve the performance and this case will not happen if use the normal way source collection,  it will only validate visible request parameters.

**Comment by lyiyu66** [comment]
According to the comment https://github.com/vmware/singleton/issues/2077#issuecomment-1423801258, it is ok to make it won't fix.
