### ISSUE TITLE
[BUG] [Singleton Angular Client]Upper case language and lower case region in init function can't be identified in language and region drop down list.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#208]
**Describe the bug**
Language and region is sensitive in init function.
Upper case language: display "English" in language list.
Lower case region: display the default region of language. Example if user defines the language as "JA" and region as "fr", then "JP" will be selected in region list.

**To Reproduce**
1. Input "PT" as language and "fr" as region in sample app.
localeService.init('JA','fr');

**Expected behavior**
Language and region isn't sensitive in init function.
For above case, 日本语 should be selected in language list and FR in Japanese should be selected in region list.

**Additional context**
Only the language and region list are impacted. It doesn't impact to translation and pattern pipes.

**Comment by lyiyu66** [comment]
Correct the typo in reproducible step with below info:

To Reproduce 
Steps to reproduce the behavior:

Input "JA" as language and "fr" as region in sample app.
localeService.init('JA','fr');

**Comment by wangyi-e** [comment]
Not a bug.
The conclusion we discussed is that it is locale normalization feature.
