### ISSUE TITLE
[BUG] remove 2 fields (acct & domain) in claim checking when do source collection

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2104]
**Describe the bug**
When do token validation,  please remove 2 fields ((acct & domain) in claim to meet the token is from oauth app instead of a user.

**Comment by tigershi** [comment]
add the null check before set the claim fields(acct, domain, context, perms)

**Comment by lyiyu66** [comment]
Regression testing is done and no issue is found with commit fcab18cfbfa50e22ab49c3b0de5ca3c12fe7bcb5.

**Comment by nannany00** [comment]
Testing for the change is pass on fcab18cfbfa50e22ab49c3b0de5ca3c12fe7bcb5
