### ISSUE TITLE
[BUG] [Java service] Change the About Version API Error Message Error Level

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#2106]
For other API like get component translation, if I use a product name which does not exist, the response would be '"message": "The product 'xxx' is NOT supported yet!", but in this API '/i18n/api/v2/about/version', it shows '[FATAL ERROR]Failed to get version info for xxx/xxx' . It is a business error should use error level message.

expect:
Change the message "[FATAL ERROR]Failed to get version info for xxx/xxx" to "Failed to get version info for xxx/xxx"

.

**Comment by lyiyu66** [comment]
checked with commit b0b5d8e55f0b91c4198adb359803d2d894cc4534, the issue is fixed.
```
{
  "response": {
    "code": 404,
    "message": "Failed to get version info for vmware2018/1.1.0",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```
