### ISSUE TITLE
[Service][l10nAgent] Add "user-agent" in request header

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2115]
For the rule NoUserAgent_HEADER:

it requires our client to add user-agent to the request header, referring  to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent the client needs to follow the syntax 'User-Agent: <product> / <product-version> <comment>' , for our case an example is 'User-Agent: vip-scanner / 1.0.0 source collection', please add value according to real case.

**Comment by lyiyu66** [comment]
Checked with commit 401d7cb3f767cabe0e29ddd52f17733ed3b56d23, agent can forward data from remote service to local service successfully regardless of whether user-agent request header is enabled or not.
