### ISSUE TITLE
[BUG][Go Client]Should get locale list from source and translation

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#2123]
**Describe the bug**
Now go client gets available locales from translation only. If both source and translation are configured, but translation doesn't have any locales availabe, client will return empty available locales.

**To Reproduce**
1. Configure a kind of source and translation, but translation doesn't have any bundles available.
2. Get available locales, client returns empty result.

**Expected behavior**
Available locales should have source locale.

**Comment by dleng-vmware** [comment]
@Xiaochao8 Now when a non-existent product or version is requested, the localelist returned also contains en

**Comment by Xiaochao8** [comment]
> @Xiaochao8 Now when a non-existent product or version is requested, the localelist returned also contains en

For normal cases, the source should exist always.
In the case you mentioned, it's an abnormal case and users should correct the product and version. Then everything is fine.
Another reason to behave like this is because server returns empty for supported locale when 'latest' bundle is available and server doesn't provide an interface to get if source exists or not.

To sum up, this is an abnormal case and the behavior is expected.
