### ISSUE TITLE
[BUG][Java Service]Failed to start up i18n/l10n s3 services on OpenJDK9 when the build is compiled with OpenJDK11 or 8.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2124]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/b0b5d8e55f0b91c4198adb359803d2d894cc4534
Failed to start up i18n/l10n s3 services on OpenJDK9 when the build is compiled with OpenJDK11 or 8.

**To Reproduce**

1. Compile services on openjdk 8 or 11.
2. Change the build's bundle location to s3.
3. Run the jar packages on openjdk 9(build: 9.0.4 from https://jdk.java.net/archive/) environment.
4. See error log attached: [Singleton-error.log](https://github.com/vmware/singleton/files/10941399/Singleton-error.log)

**Expected behavior**
Can start and run on openjdk 9 environment.

**Comment by tigershi** [comment]
the issue caused by the openJdk9 didn't import the Amazon S3 certificates into the jdk truststore. It needn't change code to fixed it. I will write doc about it

**Comment by tigershi** [comment]
https://confluence.eng.vmware.com/display/GQ/OpenJDK+9++upgrade+the+cacerts+file

**Comment by tigershi** [comment]
This issue occurs when the SSL certificate of Amazon S3 is not imported as a trusted certificate in the truststore file: $JAVA_HOME//lib/security/cacerts
Solution 1: Change the OpenJdk9 cacerts file  by OpenJdk11 cacerts file
Solution 2: Import the Amazon S3 certificates into the truststore used by the Data Integration Service running the mapping following below steps:
Get the required Amazon certificates from https://www.amazontrust.com/repository/ 
Run keytool utility to import the certificates. The command has to be executed for each certificate that needs to be added to the truststore.

**Comment by lyiyu66** [comment]
i18n/l10n s3 services can be started up and run on OpenJDK9 when the build is compiled with OpenJDK11 or 8 with provided two solutions.
