### ISSUE TITLE
[BUG][Java Service]Some of i18n APIs are returned to 520 on Openjdk17/18 environment when the build is compiled with Openjdk11 or 8.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2125]
**Describe the bug**
commit: https://github.com/vmware/singleton/commit/b0b5d8e55f0b91c4198adb359803d2d894cc4534
Some of APIs are returned to 520 on Openjdk17/18 environment when the build is compiled with Openjdk11 or 8.
Affected bundle/versions: s3, bundle, lite
Affected apis:
v2: getI18nPatternUsingGET_1, getRegionListUsingGET, getDisplayLanguagesListUsingGET, getI18nPatternWithLanguageAndRegionUsingGET, getRranslationWithPatternUsingPOST, getRranslationWithPatternUsingGET
v1: getI18nPatternUsingGET

**To Reproduce**
1. Go to 'GET
[​/i18n​/api​/v2​/formatting​/patterns​/locales​/{locale}] Get pattern from CLDR'
2. Input required info as parameters.
3. See error
```
{
  "response": {
    "code": 520,
    "message": "Handler dispatch failed; nested exception is java.lang.IllegalAccessError: class com.vmware.i18n.utils.CommonUtil (in unnamed module @0xedf4efb) cannot access class sun.util.locale.ParseStatus (in module java.base) because module java.base does not export sun.util.locale to unnamed module @0xedf4efb",
    "serverTime": ""
  },
  "signature": "",
  "data": null
}
```

**Expected behavior**
Return 200 and correct data.

**Comment by tigershi** [comment]
it's not a bug, you can add the she start parameters java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar .

**Comment by tigershi** [comment]
It will be fixed automatic after fixed the issue and published the new pattern jar https://github.com/vmware/singleton/pull/2089

**Comment by lyiyu66** [comment]
The issue is not reproducible with parameter: start parameters java --add-exports java.base/sun.util.locale=ALL-UNNAMED -jar singleton-xxx.jar
Waiting a new pattern jar to verify.

**Comment by lyiyu66** [comment]
The issue is fixed with commits:
service: 36a7cd6cf051f5395790951c61434197448a84bf
cldr: ad09702268451b3747a2068303329bcc34cb2c96
