### ISSUE TITLE
[Security][Service][L10n] Please upgrade dependency libraries to latest version (sqlite3)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2128]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- sqlites

**Comment by lyiyu66** [comment]
The regression testing for l10n service is passed with commit fddee505f678cadb2955311b320d80146aba1848

**Comment by nannany00** [comment]
Waiting for next security check.

**Comment by nannany00** [comment]
Security check is pass.
