### ISSUE TITLE
[Improvement]Remove the automatically generated Dependabot branches from branch list.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2183]
**Describe the improvement**
Please help to remove the automatically generated Dependabot branches from branch list. These branches are generated since some PR are automatically generated by Dependabot.

**To Reproduce**
1. There are some automatically generated PRs by Dependabot.
2. Check the project's branch list:
![image](https://user-images.githubusercontent.com/51813046/227143456-cbfc58a9-3a54-49f9-bc58-c26cd867fe32.png)

**Expected behavior**
No Dependabot branch is created in branch list.

**Comment by junw-33455432** [comment]
Those dependabot generated PRs has been closed and relevant branches has been removed.
