### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version(spring-boot)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2185]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:
- spring-boot(2.7.8)

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
Regression testing is passed with commit 36a7cd6cf051f5395790951c61434197448a84bf.
Hence closing.
