### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (snakeyaml)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2187]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- snakeyaml(1.33)

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
Regression testing is passed with commit 36a7cd6cf051f5395790951c61434197448a84bf.
Hence closing.
