### ISSUE TITLE
[BUG][Java Service]Return 400 when key or source value includes angle brackets <> in key-based APIs.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2197]
**Describe the bug**
commit: 36a7cd6cf051f5395790951c61434197448a84bf
Return 400 when key or source value includes angle brackets <> in key-based APIs.
Effected APIs:
V2:
GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys]
GET [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys​/{key}]
POST [​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys​/{key}]
V1: all key-based APIs

**To Reproduce**
1. Go to 'GET
[​/i18n​/api​/v2​/translation​/products​/{productName}​/versions​/{version}​/locales​/{locale}​/components​/{component}​/keys​/{key}]' API.
2. Input valid data to required parameter and "<title>af</title>" as source parameter.
3. Send the request and check the response:
```
{
  "code": 400,
  "message": "Incorrect 'source' with html tags",
  "serverTime": ""
}
```

**Expected behavior**
Should get 200 and input source as source and translation value.

**Comment by linr211** [comment]
By the security scanning, the tag such as '<title>af</title>' is considered as risky content now.
