### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2236]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

sqlite (3.41.0.0) -> 3.41.2.1

**Comment by nannany00** [comment]
Security check is pass.

**Comment by lyiyu66** [comment]
The regression test is passed with commit e0d33f09b7577adbb318016cd3197807077d1341
