### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (spring-boot)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2295]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- spring-boot(2.7.10)

**Comment by lyiyu66** [comment]
Regression testing is done and no issue is found with commit 49c6b4bc93c3eac75d09d1626af5219b7e2a54a6

**Comment by nannany00** [comment]
Security check is pass
