### ISSUE TITLE
Please add support for ISO-639 Chinese language subtags.

### ISSUE THREAD

**Issue by jmeyer37** [vmware/singleton#233]
Development teams at Dell, Dell EMC and RSA do not use the Chinese BCP 47 subtags ZH-HANS and ZH-HANT. Please add support for the ISO-639 subtags ZH-CN and ZH-TW.

**Comment by nannany00** [comment]
Hi @jmeyer37 , 

Could you help to provide more details about this feature you mentioned, like the reproduce steps, the problem you met, etc.? 

Singleton Service uses "zh-Hans/zh-Hant" for the translation bundle file name, but a locale fallback mechanism is supported in Singleton Service, that means Singleton Service APIs work well even though you request "ZH-CN/ZH-TW", if messages_zh-Hans/t.json exisiting in correct location.

Thanks,
@nannany00  (from Singleton team)

**Comment by jmeyer37** [comment]
Internal Use - Confidential

Hi

It was my understanding that Singleton does not support ZH-CN and ZH-TW. Are you saying that it does?
Thanks
John

**Comment by nannany00** [comment]
Hi @jmeyer37 ,

Yes, Singleton supports zh-CN/zh-TW for all APIs.

Thanks,
@nannany00

**Comment by gong-yu** [comment]
Hi @jmeyer37,

Could you double confirm if the answer is clear enough for you? If the current Singleton Service behavior has met your requirement, i will close this issue then.

**Comment by gong-yu** [comment]
Close the issue as Singleton does support ISO-639 locale codes.
