### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (spring-boot-autoconfigure)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2345]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- spring-boot-autoconfigure(2.7.11)

**Comment by lyiyu66** [comment]
No regression issue is found with commit 43d048082a0e278283e21f111b664fb774abf166

**Comment by nannany00** [comment]
Security check is pass.
