### ISSUE TITLE
[BUG][Java Service]Response data contain plurals when requesting "currencies" pattern for language(zh-hans) and region(CN) with pattern API.

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2358]
**Describe the bug**
[BUG][Java Service]Response data contain plurals when requesting "currencies" pattern for language(zh-hans) and invalid region(CN) with pattern API.

**To Reproduce**
1. Go to 'i18n/api/v2/formatting/patterns'
2. Input "zh-hans" as language, "CN" as region and "currencies" as pattern.
3. See the response:
<img width="825" alt="image" src="https://github.com/vmware/singleton/assets/82644009/f0005282-9331-46ae-bf87-8c262e217e61">

**Expected behavior**
reponse data can see picture :
<img width="788" alt="image" src="https://github.com/vmware/singleton/assets/82644009/40e9c1a9-fc95-4cba-937b-497257d07b23">

commit : ea05b63f2c66ec90bd32cf60187fbe0125b46922

**Comment by huihuiw01** [comment]
After discussion, developers(backend&frontend) and testers arrived consistent opinion, plural data should be returned with currency data, so this is not a bug.

**Comment by JiLiang888** [comment]
currency，numbers，plurals data  returned when "currencies" as pattern.
