### ISSUE TITLE
[REQUIREMENT][Go Service] Support localized timezone list 

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2365]
Is your feature request related to a problem? Please describe.
I need to get a localized timezone list from Singleton Service, it should have same feature with java service.

Describe the solution you'd like
Add an API in Singleton Service to get a localized timezone list from CLDR

Describe alternatives you've considered
A clear and concise description of any alternative solution or feature you've considered.

Additional context

**Comment by JiLiang888** [comment]
pass
[80921d9](https://github.com/vmware/singleton/commit/80921d9c0e57ae6e184f2df2b1091705f48e2333)
