### ISSUE TITLE
[REQUIREMENT][Go service]Support to get the build's version information.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2369]
**Is your feature request related to a problem? Please describe.**
Support to get the build's version information. Java service has such feature, it should be implemented in Go service as well.

**Describe the solution you'd like**
GET ​/i18n​/api​/v2​/about​/version
Get the build's version information, including service's version info and product's translation's version info.

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by JiLiang888** [comment]
https://confluence.eng.vmware.com/pages/viewpage.action?pageId=1774087487

**Comment by JiLiang888** [comment]
test complete ;
https://github.com/vmware/singleton/issues/2600
https://github.com/vmware/singleton/issues/2615
