### ISSUE TITLE
[REQUIREMENT][Go service]Support to get multiple keys' translation.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2370]
**Is your feature request related to a problem? Please describe.**
Support to get multiple keys' translation. Java service has such feature, it should be implemented in Go service as well.

**Describe the solution you'd like**
GET /i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys
Get mult-keys' translation in specific component

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by JiLiang888** [comment]
test complete  and pass ; 

<img width="1178" alt="image" src="https://github.com/vmware/singleton/assets/82644009/4322a72e-953c-4ab9-88e4-10c9585b2f56">
