### ISSUE TITLE
[REQUIREMENT] [Go Service] Go Service support ASCII characters as key name , same as java service

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2373]
**Describe the bug**
Go Service support ASCII characters as key name, includes some symbols

**To Reproduce**
1.Go Service support ASCII characters as key name, includes some symbols,such as : 
"11>#$\\AB@<key*+1n:a%me|A^;[-}%!~?d/f[c\"c]^_`{|y}io>": "testing for ja-JP",
2. api :translation-product-component-key-api/get_translation_products__productName__versions__version__locales__locale__components__component__keys__key_

**Expected behavior**
translation-product-component-key-api can get translation for ASCII characters as key name ,as picture :

<img width="1434" alt="image" src="https://github.com/vmware/singleton/assets/82644009/1d363421-aa22-464c-8221-21dad976a1e1">

commit https://github.com/vmware/singleton/commit/fb3c0bb0db9b2cac59097d3250c10e4cbf180998

**Comment by JiLiang888** [comment]
if key contail /  , still can't get translation; such as :
**"Key/1" : "string",**
response : 404 page not found

**Comment by Xiaochao8** [comment]
> if key contail / , still can't get translation; such as : **"Key/1" : "string",** response : 404 page not found [80921d9](https://github.com/vmware/singleton/commit/80921d9c0e57ae6e184f2df2b1091705f48e2333)

This is expected. The special characters should be encoded.

**Comment by lyiyu66** [comment]
That is nothing about html or base64 encoding, it is GET key API. The slash(/) should be supported since Java already support it.

**Comment by JiLiang888** [comment]
https://github.com/vmware/singleton/issues/2480
