### ISSUE TITLE
[REQUIREMENT] [Go Service]Support more data in dates pattern, same as java service

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2416]
**Describe the bug**
[BUG] [Go Service]Support more data in dates pattern, same as java service

**To Reproduce**
1. Go to '[formatting-pattern-api]'
2. input language=en, region=us,scope=dates 
3. see response data : dayPeriodsFormat is missing some data compare with java service  
<img width="869" alt="image" src="https://github.com/vmware/singleton/assets/82644009/8f72e777-cd7b-4c59-bb1f-a567d66bd121">
<img width="1105" alt="image" src="https://github.com/vmware/singleton/assets/82644009/9f163450-3743-448e-b59c-0505a8546b25">

**Expected behavior**
same as java service

**Comment by lyiyu66** [comment]
The expected data can be shown on go service with commit 2ee15aa8da722e980cad0664283f4c719db5a289:
![image](https://github.com/vmware/singleton/assets/51813046/ed9a7ada-3060-4cf1-9e5c-03f09731362f)
