### ISSUE TITLE
[BUG] [Singleton Service] Don't support locale fallback in multiple-component API

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#244]
**Describe the bug**
Add a new API in Singleton Service v2: get translation by multiple-component, but it only supports full match for locale parameter, no locale fallback mechanism.

**To Reproduce**
1. Start the latest Singleton Service build
2. Switch to v2 API list
3. Find the multiple-component API
GET
/i18n/api/v2/translation/products/{productName}/versions/{version}/multlocales/{locales}/multcomponents/{components}
4. Translation bundle for "zh-Hans" exit in Singleton service, but nothing returned when request locale="zh-CN"

**Expected behavior**
Locale fallback mechanism should be supported in this API, the same behavior with get translation by Single component.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by tigershi** [comment]
fallback is implemented by client side

**Comment by nannany00** [comment]
This Singleton service lite version can be found under `singleton/publish` folder now.
