### ISSUE TITLE
[BUG] [Go Client][Smoke Test]Please remove this line of code from the travis.yml file because it downloads the latest goconvey version which may conflict with the version required in smoke test

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2443]
**Describe the bug**
[BUG] [Go Client][Smoke Test]Please remove this line of code from the travis.yml file because it downloads the latest goconvey version which may conflict with the version required in smoke test

**To Reproduce**
1. Go to 'https://github.com/vmware/singleton/blob/g11n-go-client/.travis.yml'
2. remove this : 
    go get github.com/smartystreets/goconvey
<img width="1117" alt="image" src="https://github.com/vmware/singleton/assets/82644009/f8c7c79e-21f9-4ef3-90d2-3aec2cfc13f4">

**Expected behavior**
remove this code as screenshot displayed

**Comment by junw-33455432** [comment]
PR has been created to fix the issue: https://github.com/vmware/singleton/pull/2455
@JiLiang888 Please help to update the end line "replace" in https://github.com/vmware/singleton/blob/devops/autotest/client/go/goclienttest/go.mod , change lib from dleng's repo to vmware/singleton repo to fix another failure in smoke test.

**Comment by dleng-vmware** [comment]
PR has been created to remove the useless code: https://github.com/vmware/singleton/pull/2464
