### ISSUE TITLE
[Security][JAVA Client] Please upgrade dependency libraries to latest version (jackson-databind)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2448]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

- jackson-databind (2.14.0)

**Comment by huihuiw01** [comment]
This issue has been fixed by PR #2425. Just need @renligeng help publish a new pattern build for Singletion Service and Java Client to consume.

**Comment by huihuiw01** [comment]
Below is the new published pattern build:
https://repo1.maven.org/maven2/com/vmware/singleton/singleton-i18n-patterns-core/0.5.15/

Please rerun the security scan to verify.

**Comment by nannany00** [comment]
Security check is pass

**Comment by lyiyu66** [comment]
The regression testing is PASS on commit dd76e3c9cef264bcedafb45e0d776bc041d40d04

**Comment by lyiyu66** [comment]
Regression testing (include java client invoke pattern package) on pattern lib package and java service is PASS.
