### ISSUE TITLE
[devops] create a new branch with the name 0.6.x from the tagged master branch and set up CI.

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2468]
After a new tag 0.6.15 for Singleton Service from master branch is created, please
- Create a new branch named 0.6.x from 0.6.15 tag
-  Setup CI for this new branch 0.6.x

**Comment by nannany00** [comment]
Tag: https://github.com/vmware/singleton/releases/tag/v0.6.15-Singleton-Service

**Comment by tigershi** [comment]
there still has issue in CI‘s Codacy Static Code Analysis stage

**Comment by tigershi** [comment]
The PR have worked successfully
