### ISSUE TITLE
[REQUIREMENT][Service] Merge SaaS and lite versions

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#248]
**Is your feature request related to a problem? Please describe.**
Singleton Service currently has 2 versions: 
1) one served for SaaS products with full set of features such as machine translation, S3 storage support, database support, swagger UI, etc; 
2) the other served for on-prem products with only core functionalities for creating smaller footprint.

Now the code for SaaS version is open sourced already while those for lite version is still maintained in VMware internally. Singleton team has to maintain 2 copies of code and 2 types of Singleton Service build, which increases the devops effort.

**Describe the solution you'd like**
Open source  the code for lite version and manage them together with SaaS version.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nannany00** [comment]
Build works well and regression testing is PASS.
