### ISSUE TITLE
[REQUIREMENT][Go service]Support to fall back the existing version's data if there is only one version bundle.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2483]
**Is your feature request related to a problem? Please describe.**
Support to fall back the existing version's data if there is only one version bundle.

**Describe the solution you'd like**
This mechanism doesn't affect the product that includes multiple versions, the previous version fallback mechanism is kept.
When requesting product includes only one version bundle, the new mechanism will be worked:
Return the existing version's info no matter which version(valid version name) user is requesting.
It should take effected on all v2 GET APIs that are related with translation:
/i18n/api/v2/translation/products/{productName}/versions/{version}/**
/i18n/api/v2/combination/translationsAndPattern    
/i18n/api/v2/locale/supportedLanguageList
/i18n/api/v2/about/version

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by JiLiang888** [comment]
test pass
commit bfa3e1d5d36b9f98a4382d3b3ecd60f4d81209d3
