### ISSUE TITLE
[REQUIREMENT]Incrementally update translations

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#249]
**Is your feature request related to a problem? Please describe.**
Every time i want to update translation(s) for a product, i have to push the whole translation bundle to Singleton Service even only one string is updated. This will introduce potential impact to performance when transferring large set of data between Singleton Service and clients.

**Describe the solution you'd like**
Only updated translations should be downloaded from Singleton Service.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tigershi** [comment]
We have discussed it and done the design. Because of the it need to change a lot in service side and can't use it in SAAS environment. We decide that we can't do it

**Comment by gong-yu** [comment]
Reopen this requirement

**Comment by gong-yu** [comment]
Remove this requirement from Sprint 73. need more discussion.
