### ISSUE TITLE
[Security][Service] Please upgrade dependency libraries to latest version (guava)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2533]
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:
- guava(30.1.1-jre)

**Comment by lyiyu66** [comment]
Services regression testing are PASS with commit a2ac375e565f02a95e2bcc94a4fc521084d8362c

**Comment by lyiyu66** [comment]
Twistlock security check on 08/21 is PASS.

**Comment by lyiyu66** [comment]
OSSPI security check(0.7.x and 0.6.x) on 09/21 are PASS.
