### ISSUE TITLE
[L10nAgent] To support customize body size when forward source

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2566]
Currently, our l10nAgent can customize the key number in body when forward source, but sometime the limitation will work for body size, so please also support to customize body size.

**Comment by Kai-kevin** [comment]
At present, it has affected the newly added singleton products, and needs to be fixed asap.

**Comment by lyiyu66** [comment]
The testing is done, one issue is found: 
https://github.com/vmware/singleton/issues/2589
