### ISSUE TITLE
[BUG] [L10nAgent]The last key will be lost if the last key leads to the body size is more than the defined requestbody size.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2587]
**Describe the bug**
commit: 6079fff196a9a48c9a4e563c8ad2d1741d8462df
The last key will be lost if the last key leads to the body size is more than the defined requestbody size.

**To Reproduce**
1. There is 4 keys in a messages_latest.json file, and body size of the first 3 keys is less than 1M(the defined requestbody size), but plus the 4th key, their size are more than 1M.

- key1 + key2 + key3 < 1M,  
- key1 + key2 + key3 + key4 > 1M
- batch size = 4, requestbody size = 1M

2. Put above file to a supported product/version/component folder in l10nagent  local source location.
3. Start l10nagent service
4. Check the log and target received service's bundle:
the sent source size is 3 in log and there is 3 keys are received in bundle.

**Expected behavior**
All 4 keys should be send out in 2 batches(3keys + 1key) and 4 keys can be received in bundle.

Notes: if there are 5 keys in that file, the issue will not be reproducible.

**Comment by lyiyu66** [comment]
Set it as low priority since the required reproducible condition is the key must be the last key and it causes the batch body size is more than defined value.  If it is not the last key, the issue can't reproducible.  That means if the value of batch size is less than the file's key count, the issue appear hardly all most.

**Comment by tigershi** [comment]
I tend to think set the labels to medium, because it lost the source

**Comment by lyiyu66** [comment]
The issue is fixed with commit 35ce51874fee6fc98084745e132c7832c29b30e8
