### ISSUE TITLE
[Security] [Java Service] [Java Client] Review and fix PR reported from Dependbot in Code Review

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2593]

**Comment by tigershi** [comment]
All the task have finished

**Comment by tigershi** [comment]
https://github.com/vmware/singleton/pull/2681, 
https://github.com/vmware/singleton/pull/2682,t
https://github.com/vmware/singleton/pull/2650
because these only use in test stage and have Compatibility issue decide closed
