### ISSUE TITLE
[BUG] [Go Service]Response code is 207 when fail to get service information and bundles information in about-version-api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2600]
**Describe the bug**
[BUG] [Go Service]Response code is 207 when fail to get service information and bundles information in about-version-api

**To Reproduce**
1. Go to about-version-api
2. input product name= VMwareVIP2018,version=1.0
3. see response is 207
<img width="1083" alt="image" src="https://github.com/vmware/singleton/assets/82644009/780f7521-598b-467d-8639-3a3a6b52267b">

**Expected behavior**
"response": {
        "code": 404,
        "message": "Failed to get version info for VMwareVIP2018/1.0"

6cd6319be3792b0702a5cf9d4370d4294b683881

**Comment by lyiyu66** [comment]
The message code issue is fixed with commit b61ecc2a01e54a50f92c30ff93a5e2edd33942d9:
![image](https://github.com/vmware/singleton/assets/51813046/ddfd5240-2f65-490e-affb-2534637bc75c)
