### ISSUE TITLE
[BUG] [Go Service]should response 404 when high version fallback to a version without bundle info in about-version-api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2620]
**Describe the bug**
[BUG] [Go Service]should response 404 when high version fallback to a version without bundle info in about-version-api

**To Reproduce**
**go service build without service info**
1. Go to 'about-version-api'
2. input product name = vmware2018 ;version = 5.0
3. See response code 604

<img width="1459" alt="image" src="https://github.com/vmware/singleton/assets/82644009/b19ba296-6297-4fe3-a584-c86908b39b50">

**Expected behavior**
{
  "response": {
    "code": 404,
    "message": "Failed to get version info for vmware2018/1.1.0",
    "serverTime": ""
  },

TestData:
1.product(vmware2018) with two version (1.0  1.1.0)
2. under 1.0 version exist version.json , and 1.1.0 version didn't exist version.json;

6cd6319be3792b0702a5cf9d4370d4294b683881

**Comment by lyiyu66** [comment]
The error code issue is fixed with commit b61ecc2a01e54a50f92c30ff93a5e2edd33942d9:
![image](https://github.com/vmware/singleton/assets/51813046/6466fa0a-a9a2-4bc2-8b0d-8fa6c13e7c43)
