### ISSUE TITLE
[BUG] [Go Service]reponse message is incorrect when allowlistEnable in translation-sync-api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2667]
**Describe the bug**
[BUG] [Go Service]reponse message is incorrect when allowlistEnable in translation-sync-api

**To Reproduce**
**allow list is on** 
1. Go to 'translation-sync-api'
2. Input product name= vmware-vip , version= 1.0 ; post data below :
{
  "data": {
    "creation": {
      "operationid": "string"
    },
    "dataOrigin": "string",
    "productName": "VMwareVIP2018",
    "translation": [
      {
        "component": "Test.ABC_abc-123",
        "locale": "es-419",
        "messages": {
          "additionalProp1": "string",
          "additionalProp2": "string",
          "additionalProp3": "string"
        }
      }
    ],
    "version": "1.0"
  },
  "requester": "string"
}
3. See response
{
  "response": {
    "code": 400,
    "message": "Product 'vmware-vip' doesn't exist"
  }
}

**Expected behavior**
{
  "response": {
    "code": 400,
    "message": "ProductName can only contain alphanumeric characters"
  }
}

commit bfa3e1d5d36b9f98a4382d3b3ecd60f4d81209d3

**Comment by Xiaochao8** [comment]
`allow list` take precedence over product name verification.
This is expected.
