### ISSUE TITLE
[l10n][BUG]Lost key when the messages_latest.json file in S3 is locked more than 30s during source collection.

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#2670]

**Comment by lyiyu66** [comment]
Regression testing and above concurrent testing(100 and 50 threads for one l10n instance) are PASS with commit 30dcfe321eeac05e989e9375563ba76465b4b62f
No regression issue and no key is lost. And there will be a folder /l10n/tmp/excep to store request files where an error occurred during the request process.
