### ISSUE TITLE
[Documentation][Java Service] Update readme and open-source doc after JDK upgrade

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#2694]
After spring-boot upgrade of Singleton Java service, we support to run service on both jdk8 and jdk17, please  also update readme and open-source website for this part.

**Comment by tigershi** [comment]
the Readme site: https://github.com/vmware/singleton/blob/master/README.md

**Comment by lyiyu66** [comment]
The jdk17 has been mentioned on master branch readme.md file
