### ISSUE TITLE
[BUG] [Java Service]Response data should remove duplicate data if request dup version in get multiVersion translation api

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2700]
**Describe the bug**
[BUG] [java service]Response data with repeat data if request dup version in get multiVersion translation api

**To Reproduce**
1. Go to '/i18n/api/v2/translation/products/{productName}/multiVersionKey'
2. Request parameters as 
<img width="1164" alt="image" src="https://github.com/vmware/singleton/assets/82644009/95cf0f59-c65d-42c1-9c74-ce2831fbd277">

3. See response 
response code =200 ;

<img width="1110" alt="image" src="https://github.com/vmware/singleton/assets/82644009/a2a0e1a1-f223-4f36-820d-da93294aeda8">

**Expected behavior**
response data should remove duplicate data

build.number.buildnumber=30dcfe321eeac05e989e9375563ba76465b4b62f

**Comment by tigershi** [comment]
The same issue with https://github.com/vmware/singleton/issues/2702

**Comment by JiLiang888** [comment]
pass 

build.number.buildnumber=f25e9d564eb33598f596db4bd62a2ef6d47724cf
