### ISSUE TITLE
 [BUG] [Go Service]Should verify when request only parameter in about-version-api 

### ISSUE THREAD

**Issue by JiLiang888** [vmware/singleton#2721]
**Describe the bug**
 [BUG] [Go Service]Should verify when request only parameter in about-version-api 

**To Reproduce**
1.Go to 'about-version-api'
2.input product name = vmware2018 ;version = null
3.See response code 200
<img width="797" alt="image" src="https://github.com/vmware/singleton/assets/82644009/80f7a588-2408-4c91-892c-b68c7faee1ba">

**Expected behavior**
"response": {
    "code": 400,
    "message": "Only one parameter of 'productName' and 'version' is provided, they should be used in pairs!",

commit 5466146a03652634432a76a97652b550b9b51e19

**Comment by Xiaochao8** [comment]
duplicate to #2615
