### ISSUE TITLE
[BUG] [Java Client]Fail to use getString() for getting translation with argument on shared component.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#273]
**Describe the bug**
Get English source back when using getString() to request translation with argument.

**To Reproduce**
1. There are main module and shared module.
2. Register shared module config info to main.
3. Request the shared component's translation with argument with getString().

The GET HTTP Request send out is correct, but the translation is English.

**Expected behavior**
Can get the translation with argument correctly.

**Additional context**
Not reproducible if the translation without argument.

**Comment by linr211** [comment]
How to define the shared module in your test case? please paste your test codes here.

**Comment by lyiyu66** [comment]
public class sharedcomponent extends TestBase {

       TranslationMessage mainTranslation;
       TranslationMessage subTranslation;
       String mainProductName = "JavaClient";
       String subProductName = "JavaClientSub";
       VIPCfg mainvipCfg;
       VIPCfg subvipCfg;

       @BeforeClass
       public void preparing() throws VIPClientInitException {
    	  initVIPServer();
    	
       }

       public void initVIPServer() throws VIPClientInitException {
          mainvipCfg = VIPCfg.getInstance();
          mainvipCfg.initialize(Utils.removeFileExtension(Constants.VIP_CONFIG_FILE_NAME));
          mainvipCfg.initializeVIPService();
          mainvipCfg.createTranslationCache(MessageCache.class);
          mainvipCfg.createFormattingCache(FormattingCache.class);
          I18nFactory i18n = I18nFactory.getInstance(mainvipCfg);
          mainTranslation = (TranslationMessage) i18n.getMessageInstance(TranslationMessage.class);
        
          subvipCfg = VIPCfg.getSubInstance(subProductName);
          subvipCfg.initialize(Utils.removeFileExtension(Constants.VIP_CONFIG_SUB_FILE_NAME));
          subTranslation = (TranslationMessage) i18n.getMessageInstance(TranslationMessage.class, subvipCfg);
       }


       @Test(enabled=true, priority=1, dataProvider="subTranslatonString")
       @TestCase(id = "002", name = "translation_GetSubModuleTranslation_getString", priority = Priority.P1, description = "get sub module translation with getString")
       public void getsubMessageByString(Locale locale, String component, String key, String source, String comment, Object[] args, String expected) {
       String translation1 = subTranslation.getString(locale, component, key, source, comment, args);
       log.verifyEqual("Get translation successfully with getString", translation1, expected);
       }


       @DataProvider(name = "subTranslatonString")
       public Object[][] subTranslationString() {
		String component = TestDataConstant.SUB_COMPONENT_SHAREDCOMPONENT;
		String key = "sub.messages.sentence";
		String source = "sub.messages.sentence";
		String comment = "this is comment";
		String[] args = {"HOW THE STEEL WAS TEMPERED", "Lei"};
		
		
		return new Object[][]{
			{
				TestDataConstant.SUB_LOCALE_STANDARD,
				TestDataConstant.SUB_COMPONENT_SHAREDCOMPONENT,
				TestDataConstant.SUB_KEY_STANDARD,
				TestDataConstant.SUB_SOURCE_STANDARD,
				comment, null, TestDataConstant.SUB_TRANSLATION_STANDARD},
			{
				new Locale("ja"), component, key,
				source, comment, args,
				String.format("ブック '%s' は  '%s' に属します", args[0], args[1])}
		};
    }

**Comment by lyiyu66** [comment]
Can't reproduce. Hence closing.
