### ISSUE TITLE
[BUG][GO Service]localeID is empty when language is language-script type, scope is plurals/dateFileds/measurements and combinational locale is valid.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2796]
**Describe the bug**
localeID is empty on language/region pattern api when following conditions are met: 

1. language is language-script type
2. scope is plurals/dateFileds/measurements
3. combinational locale is valid.

Impacted APIs:
GET [/formatting/patterns](http://<hostname:port>/i18n/api/v2/swagger/index.html#/formatting-pattern-api/get_formatting_patterns)
GET [/combination/translationsAndPattern](http://<hostname:port>/i18n/api/v2/swagger/index.html#/translation-with-pattern-api/get_combination_translationsAndPattern)
POST [/combination/translationsAndPattern](http://<hostname:port>/i18n/api/v2/swagger/index.html#/translation-with-pattern-api/post_combination_translationsAndPattern)

**To Reproduce**
1. Go to 'GET ​​/formatting​/patterns'
2. Input "zh-Hans" as language, "TW" as region and "plurals" as pattern.
3. See the response:
![image](https://github.com/vmware/singleton/assets/51813046/1ea2cde2-3817-40ee-90ba-1f8a56927911)

**Expected behavior**
localeID should be the valid combinational locale
```
{
  "response": {
    "code": 200,
    "message": "OK"
  },
  "data": {
    "localeID": "zh-Hant",
    "language": "zh-Hans",
    "region": "TW",
    "categories": {
      "numbers": {
...
```

**Comment by Xiaochao8** [comment]
Since there isn't a valid locale from language `zh-Hans` and Region `TW`, and the response pattern data are from different locales. The result is expected.

**Comment by lyiyu66** [comment]
Closing it since above comment.
