### ISSUE TITLE
[Service] add switch in put API

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#2848]
add a switch in singleton service API

**Comment by tigershi** [comment]
when set configuration item translation.update.enable=false，access v1 and v2 put API will response 
{
    "code": 404,
    "message": "Not Found"
  }

**Comment by lyiyu66** [comment]
PUT api can work correctly when switch is true or false with commit https://github.com/vmware/singleton/commit/b47cb100af23f5d9f4b8786c18ccdcd5a604fa33
