### ISSUE TITLE
[BUG] Java client sample app compile failed

### ISSUE THREAD

**Issue by surite** [vmware/singleton#288]
**Describe the bug**
'gradle build' command executes failed with following error: 

> Task :compileJava FAILED
/Users/sur/Opensource/surite/g11n-java-client/sample-client-app/src/main/java/com/vmware/vipclient/sample/Main.java:30: error: unreported exception VIPClientInitException; must be caught or declared to be thrown
                cfg.initialize("sampleconfig");
                              ^
1 error

FAILURE: Build failed with an exception

**Comment by linr211** [comment]
since it's fixed, close it.
