### ISSUE TITLE
[BUG][0.6.x][Java][Security] Please upgrade dependency libraries to latest version: org.owasp.esapi_esapi version(2.5.2.0)

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#2895]
commit:668e3b97218fc2e479c780a62dccabc1dfe4d864
In Singleton Service build, below dependency library is out of date, please upgrade it to latest version:

org.owasp.esapi_esapi version(2.5.2.0)
[GHSA-r68h-jhhj-9jvm](https://github.com/advisories/GHSA-r68h-jhhj-9jvm)

**Comment by tigershi** [comment]
fixed in PR: https://github.com/vmware/singleton/pull/2898

**Comment by lyiyu66** [comment]
commit: ac378147da8d9839af5ce0c5ad267da23691c222
Security check: OSSPI & Twistlock: PASS
Regression testing: PASS
