### ISSUE TITLE
[BUG] [JAVAClient] Long source string is cut when being collected dynamically

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#307]
When sending long string to service through dynamic source collection, string is cut,

Here is the test script pic from product team. The string on service is cut, so getMessage always returns English becuase source is different.

Locale locale = new Locale("zh", "CN");
        String message = "xxxxxx";
        String key = "xxx";
        String result = this.translation.getString(locale, "xxx", key, message, "");
        // result should be translated to zh_CH, that's why will not be equal to message
        Assert.assertNotEquals(message, result);

**Comment by nannany00** [comment]
@Xiaochao8 , please help to check this issue. Thanks.

**Comment by lyiyu66** [comment]
Checked with latest build, client can transfer the long source to service without any truncation.
