### ISSUE TITLE
[BUG] Failed to get multiple locales' pseudo strings with translation-product-api.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#335]
**Describe the bug**
Failed to get multi locales' pseudo string with translation-product-api. Currently, it only return one locale(latest)'s pseudo.

**To Reproduce**
1. Using 
/i18n/api/v2/translation/products/{productName}/versions/{version} API and request multiple locales(en-US, ja. de)' pseudo strings.

**Expected behavior**
Should have all locales' pseudo returned.

**Comment by tigershi** [comment]
the design behave is only return pseudo strings
