### ISSUE TITLE
[BUG] [Singleton Service] Don't support version fallback in getSupportedLanguageList API

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#338]
**Describe the bug**
Version fallback feature is added for related translation APIs, this feature mean: when the product upgrade to a newer release, and the translation is not ready for the newer release, Singleton Service will return the translation of previous version as fallback. 
But now, the language list if product get from Singleton Service still is null.

**To Reproduce**
1. Start the Singleton Service build
2. Go to API: **GET /i18n/api/v2/locale/supportedLanguageList Get the supported language list**
3. The Testing data:
Testing/1.0.0
When try to get translation for Testing/2.0.0, it can return well, but for language list, it will return 404 error as below:
```
{
  "response": {
    "code": 404,
    "message": "Failed to get locale list for Testing/2.0.0",
    "serverTime": ""
  },
  "signature": "",
  "data": ""
}
```

**Expected behavior**
If the translation can be returned well, then the language list should also be returned well.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Additional context**
NA

**Comment by tigershi** [comment]
With Colin's suggest, we need to schedule a meeting to discuss the version fallback content

**Comment by tigershi** [comment]
the version fallback APIs design 
https://confluence.eng.vmware.com/display/GQ/API+-+Version+Fallback
