### ISSUE TITLE
[REQUIREMENT] Create a solution to split source collection feature out from i18n manager

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#344]
**Is your feature request related to a problem? Please describe.**
Currently, i18n manager serves as translation fetcher and source collector. It increases the complexity of business logic of i18n manager. Besides, the source collection feature should not be included in the production environment.

**Describe the solution you'd like**
Remove source collection feature from i18n manager, use a separate source collection service to collect translatable resources.

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by Xiaochao8** [comment]
Pending on Gateway design
