### ISSUE TITLE
[REQUIREMENT][Service] Support more formatting options for language list API

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#361]
**Is your feature request related to a problem? Please describe.**
For the language list data that provided to product team, they have different usages, for example: the language can be used in middle of sentence; or in select list/menu; or isolated UI element.
Now Singleton only provides one option: the language used in middle of sentence, we also need other options.

**Describe the solution you'd like**
Actually, in CLDR, there're 4 options for capitalization, please refer to
[http://cldr.unicode.org/development/development-process/design-proposals/grammar-and-capitalization-for-date-time-elements](http://cldr.unicode.org/development/development-process/design-proposals/grammar-and-capitalization-for-date-time-elements)
[https://www.unicode.org/reports/tr35/tr35-29.html#Context_Transform_Elements](https://www.unicode.org/reports/tr35/tr35-29.html#Context_Transform_Elements)

**Describe alternatives you've considered**
Add other options to getSupportedLanguageList API.

**Additional context**
CLDR capitalization pattern data: [https://github.com/unicode-cldr/cldr-misc-full/blob/master/main/en/contextTransforms.json](https://github.com/unicode-cldr/cldr-misc-full/blob/master/main/en/contextTransforms.json)

**Comment by huihuiw01** [comment]
According to cldr version(32.0.0) we use, 
corresponding LDML doc should be:
https://www.unicode.org/reports/tr35/tr35-49/tr35-general.html#Context_Transform_Elements

corresponding CLDR capitalization pattern data:
https://github.com/unicode-cldr/cldr-misc-full/blob/32.0.0/main/en/contextTransforms.json

reference for handling titlecase-firstword:
http://cldr.unicode.org/development/development-process/design-proposals/consistent-casing
