### ISSUE TITLE
[BUG][Service] some files don't have license info

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#366]
I found some files in service code don't have license information, fox example: TranslationWithPatternAction.java

**Comment by tigershi** [comment]
I have written a program to scan the license info, the following is the list:
--------------------------begin to scan lience file--------------------------------------
singleton\g11n-ws\modules\md-restful-api-i18n\src\main\java\com\vmware\vip\i18n\api\v1\utils\AESUtil.java
singleton\g11n-ws\modules\md-restful-api-i18n\src\main\java\com\vmware\vip\i18n\api\v1\utils\EncryptUtil.java
singleton\g11n-ws\modules\md-restful-api-i18n\src\main\java\com\vmware\vip\i18n\api\v1\utils\KeyService.java
singleton\g11n-ws\modules\md-restful-api-i18n\src\main\java\com\vmware\vip\i18n\api\v1\utils\SignatureUtil.java
singleton\g11n-ws\modules\md-restful-api-i18n\src\main\java\com\vmware\vip\i18n\api\v1\utils\TokenUtil.java
singleton\g11n-ws\vip-manager-i18n\src\test\java\com\vmware\vip\i18n\api\v2\combine\TranslationWithPatternTest.java
singleton\g11n-ws\vip-manager-l10n\src\test\java\com\vmware\test\TestModels.java
singleton\g11n-ws\vip-manager-lite-i18n\src\main\java\com\vmware\vip\core\conf\LiteWebConfiguration.java
singleton\g11n-ws\vip-manager-lite-i18n\src\main\java\com\vmware\vip\core\Interceptor\LiteAPICrossDomainInterceptor.java
singleton\g11n-ws\vip-manager-lite-i18n\src\main\java\com\vmware\vip\LiteBootApplication.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\authentication\AuthenticationAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\authentication\KeyAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\CacheUtil.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\ConstantsForTest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\GitTranslationFetcherMainForTest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\MessageUtil.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\RequestUtil.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\ResponseUtil.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\common\TranslationFetcherTest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\date\DateAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\locale\LocaleAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\pattern\PatternAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationComponentAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationKeyAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationProductAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationProductComponentAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationProductComponentKeyAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationSourceAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v1\translation\TranslationSyncAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v2\formatting\pattern\FormattingPatternAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\api\v2\LocaleAPITest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\config\ConfigurationTest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\config\SpringBootTest.java
singleton\g11n-ws\vip-manager-lite-i18n\src\test\java\com\vmware\vip\i18n\l3\LocalePickupTest.java
--------------------------scan lience file end--------------------------------------

**Comment by nannany00** [comment]
Close this one, to track it by another issue: https://github.com/vmware/singleton/issues/386
