### ISSUE TITLE
[BUG] [Go Client] No component return if one of requesting component is not existing even though the another is available. 

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#384]
**Describe the bug**
No component return if one of requesting component is not existing even though the another is available when using get multiple components translation.

**To Reproduce**
coms := []string{Defaultcom, "non-existing-component"}
commsg, _ := translation.GetComponentsMessages("en", coms)
So(len(commsg), ShouldEqual, 1)

Size of commsg is 0 even though Defaultcom is available.

**Expected behavior**
 Defaultcom translation should be returned as it is a available component.

**Comment by Xiaochao8** [comment]
After discussion, we think current is proper and will keep it.

**Comment by gong-yu** [comment]
This bug will be gone after removing the multiple component support in go client (#419)
