### ISSUE TITLE
Set up branching strategy for Singleton refactoring

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#391]
Currently Singleton Service and each client has its own branch. Each branch is

**Comment by surite** [comment]
each orphan branch can have child branches.
That means we can still create new release branch like following.

master           -------------------------------------------

java client      ----------- . ---------------------------------
                                       |
                                       |
                                      V
java client release 1.0     ------------------------------

**Comment by gong-yu** [comment]
After team's discussion, we decide to use the current branch for the refactoring. We will make sure each function is backward compatible and mark those methods which will not be supported in some future version (version number TBD) as deprecated.
