### ISSUE TITLE
[REQUIREMENT][Java Client] Add capability of loading local translation bundle

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by jessiejuachon** [comment]
Shall I pick this up?

**Comment by gong-yu** [comment]
Colin will work on this task, after the PR #425 is merged.

**Comment by jessiejuachon** [comment]
I have started working on this.
