### ISSUE TITLE
[BUG] [Singleton Service] max-age doesn't work in Chrome

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#483]
**Describe the bug**
Singleton add etag and max-age of cache-control, but it still gets data from Service, not from browser cache in Chrome.

**To Reproduce**
1. Start the latest Singleton Service build on local;
2. Visit any **GET** api by https://localhost:8090/i18n/api/doc/swagger-ui.html in Chrome;
3. Open developer mode in Chrome, to check where the data from is.

**Expected behavior**
Because the max-age is 604800 by default, the data should be from Service first time; and for next calls, the data should be from browser cache.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Name: chrome 
 - Browser Version 80.0.3987.149 (64bit)

**Additional context**
1. It's not reproduced on firefox;
2. It only reproduceds on HTTPS:8090, not reproduce on HTTP:8091.

**Comment by tigershi** [comment]
As a result of the chrome security policy, the HTTPS protocol need the official certificate, Max-age feature can be use normally.

**Comment by nannany00** [comment]
If want to use max-age in Singleton service based on Chrome, there are 2 ways:
1. Singleton Service running on valid offician CA, then call APIs based on HTTPS/8090;
2. Call Singleton Service APIs based on HTTP/8091.
