### ISSUE TITLE
[Singleton Service] Mark as Deprecated for POST combination API

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#503]
In Singleton Service, there are 2 APIs to get combination data for translation and formatting pattern, one is GET, the other is POST.
Actually, the purpose is only to get data, not POST, so should remove this POST API in future.
Now we only to mark it as **[Deprecated ]** in code and swagger-ui first.

**Comment by gong-yu** [comment]
Angular Client is still using this API, need to create issue in Angular Client to change using GET API.
