### ISSUE TITLE
Performance testing for Java Client Cache Improvement

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#530]
Test the CPU/memory usage of Java client after cache mechanism change (#439)

**Comment by lyiyu66** [comment]
**Test platform**: Windows 10 Memory/16g, CPU/4, Disk/100g

**3 kinds of configurations in sample app need to be compared:**
1. old build with old mechanism - Map<String, String> map: v0.4.1-Singleton-Java-Client
2. new build with old mechanism - CacheItem cacheItem : master-1.3.289.jar
3. new build with new mechanism - CacheItem cacheItem - maxage/etag/timestamp: master-1.3.289.jar

**Sample application with below features:**
1. initialize cache is enable
2. get translation with getString()
3. get Level 2 patterns

**Peak Memory Usage(Unit: Mb)**
Request   bundle size | 5m | 10m | 20m | 30m | 50m | 70m | 100m | 200m | 300m | 400m
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
OldBuildOldMechanism | 17.2 | 19.8 | 42.7 | 104.7 | 158.1 | 183.8 | 326.1 | 553.4 | 829.6 | 1126.4
NewBuildOldMechanism | 17.2 | 25.1 | 49.9 | 110.5 | 142.8 | 197.3 | 317.2 | 529.3 | 781.8 | 1126.4
NewBuildNewMechanism | 18.5 | 17.2 | 52.8 | 102.8 | 141.3 | 198.2 | 289.6 | 558.2 | 805 | 1126.4

![image](https://user-images.githubusercontent.com/51813046/82394276-317aae80-9a7b-11ea-8de7-5adf1f1a511d.png)


**Peak CUP Usage**

Request   bundle size | 5m | 10m | 20m | 30m | 50m | 70m | 100m | 200m | 300m | 400m
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
OldBuildOldMechanism | 0.70% | 2.60% | 16.60% | 16.20% | 14.80% | 22.20% | 12.90% | 10.50% | 16.00% | 19.60%
NewBuildOldMechanism | 1.00% | 4.30% | 15.50% | 15.80% | 13.40% | 15.00% | 11.00% | 10.00% | 15.00% | 20.00%
NewBuildNewMechanism | 0.60% | 1.00% | 14.50% | 12.00% | 14.90% | 14.50% | 12.00% | 10.50% | 12% | 15.00%

![image](https://user-images.githubusercontent.com/51813046/82394480-bebe0300-9a7b-11ea-9410-d56e37091034.png)
