### ISSUE TITLE
Update JS Client API document

### ISSUE THREAD

**Issue by songjiang320** [vmware/singleton#539]
Due to current online guide for JSClient is only from README content,
But there are still many features JSClient API exposed , which need more specific guilde such as AngularClient's online guide  to describe how to use

**Comment by pengrongbo** [comment]
I have reviewed the current document, most of the features are up to date. Only one parameter needs to be updated, the 'sourceBundles' are recommended to mount source bundles instead of sourceBundle. And sourceBundles provides duplicate key checking during the array merging.

**Comment by pengrongbo** [comment]
@songjiang320 
Could you help to update this new feature in the current document?

**Comment by songjiang320** [comment]
https://github.com/vmware/singleton/pull/562

**Comment by gong-yu** [comment]
This document is applicable for js client 0.4.2.
