### ISSUE TITLE
Document about how to add new products and respective bundles 

### ISSUE THREAD

**Issue by deeDude** [vmware/singleton#547]
**Is your feature request related to a problem? Please describe.**
I have been trying to understand how to add new products, and their respective translation bundles, but nowhere on VMWare Singleton's documentation one can find something on how to do this and, also, I could not figure it out by looking at the source code as well. And it seems there arent APIs to do this. Is this a manual process? Does one need to manually add the folders for products, versions, components, and bundles?

**Describe the solution you'd like**
Properly document about how to add new products and bundles and please create the tag "vmware-singleton" on StackOverflow since it currently does not exist and it requires a user with 1500 rep to create it.

**Comment by Xiaochao8** [comment]
Hi deeDude,
Thanks for your question. We will create a document on this soon.
The tag will also be created.

**Comment by Xiaochao8** [comment]
Hi deeDude,

The tag is created, please check here.
https://stackoverflow.com/questions/tagged/vmware-singleton

**Comment by nannany00** [comment]
@deeDude , the document has been published, please refer to https://vmware.github.io/singleton/docs/overview/singleton-service/configurations/enable-new-product/
