### ISSUE TITLE
[BUG] [Java Client]New cache mechanism doesn't work on the interface of getting multiple components' translation.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#554]
**Describe the bug**
New cache mechanism doesn't work on the interface below of getting multiple components' translation:
Map<Locale, Map<String, Map<String, String>>> getStrings(final Set<Locale> locales,
            final Set<String> components)

The request isn't sent again and get the updated translation when the cache is expired. Still using the content in original cache.

**To Reproduce**
1. Set CacheExpiredTime = 0 in config file.
2. Get translation of 2 locales and 2 components with 
Map<Locale, Map<String, Map<String, String>>> result = tm.getStrings(
                Stream.of(locale, locale1).collect(Collectors.toSet()), Sets.newHashSet(component, component1));
3. Set max-age to 0 with MessageCacheItem.setMaxAgeMillis(0l).
4. Update the translation on service for changing etag purpose.
5. Send the request in step2 again.

**Expected behavior**
The request can be sent again and get the updated translation when the cache is expired.

**Comment by jessiejuachon** [comment]
The plan is to deprecate this multi-component API if sending 1 http request per component is sufficient. This is so that the client library can be more lightweight.
