### ISSUE TITLE
Database storage of bundles does not work  

### ISSUE THREAD

**Issue by deeDude** [vmware/singleton#559]
When starting _vip-manager-i18n_ with **pgdb** profile, by running BootApplication task, the following error happens:

`'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class`

Also, the application properties file for Spring profile pgdb, application-pgdb.properties, does not exist.

**Steps to reproduce the behavior**
1. On gradle.properties, set datatype to pgdb
2. Create application-pgdb.properties file 
3. Configure Spring datasources on application properties files, application-db_dev.yml, of modules **md-data-initdb** and   **md-restful-api-db** and on application-pgdb.properties
4. On application.properties file set the active profile to pgdb (spring.profiles.active=pgdb) on _vip-manager-i18n_ project
5. Run BootApplication task and notice that the service fails to get started

**Expected behavior**
The _vip-manager-i18n_ should start with no problems and the service should use the database as the storge point for the translation resources.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PostgresSQL  v9.4.8

**Additional context**
The datasource is configured like this:

`spring:
  datasource: 
    name: config
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/vip
    username: postgres
    password: postgres
    initialSize: 5
    minIdle: 5
    maxActive: 30
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    postgres:
      datasoures: 
        - name: vipdata1
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/vip
          username: postgres
          password: postgres
          initialSize: 5
          minIdle: 5
          maxActive: 30
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20j
        - name: vipdata0
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://127.0.0.1:5432/vip
          username: postgres
          password: postgres
          initialSize: 5
          minIdle: 5
          maxActive: 30
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20

**Comment by nannany00** [comment]
@deeDude , some operations are not correct, we're working on a guideline to show how to compile/use Singleton DB build.

**Comment by gong-yu** [comment]
The effort is tracked by #575.

**Comment by nannany00** [comment]
@deeDude , please have a try according to this document: https://vmware.github.io/singleton/docs/overview/singleton-service/singleton-service-db-build-introducation/
Please let me know if any issues or comments. Thanks.
