### ISSUE TITLE
[BUG] [CSharp Client]System.NullReferenceException pops up when ITranslation.Format(string locale, ISource source, params object) with bojects is "null"

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#587]
**Describe the bug**
System.NullReferenceException pops up when ITranslation.Format(string locale, ISource source, params object) with bojects is "null":
e.g 
String result =ITranslation.Format(String locale, ISource source, null)

System.NullReferenceException: Object reference not set to an instance of an object.

**To Reproduce**
1.get translation by ITranslation.Format with parameter object is null

**Expected behavior**
Can handle and no exception pop up if object is null.

**Comment by dleng-vmware** [comment]
@jin-jasper After verification, the bug still exists.
No matter how many indexes the source value has,when Format with parameter object is "null",as below
String result =ITranslation.Format(String locale, ISource source, null)
It will throws error:System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by gong-yu** [comment]
Move the issue to Sprint 90 to fix.

**Comment by dleng-vmware** [comment]
After verification, the bug was fixed.
