### ISSUE TITLE
[BUG] i18n service log always show same message

### ISSUE THREAD

**Issue by surite** [vmware/singleton#593]
**Describe the bug**
Whatever API request I send to i18n service, the log(path /logs/i18n/VIP-info.log) will always show the same message about API '/i18n/api/v1/locale/browserLocale'.

**Expected behavior**
log should show message about current request API.

**Screenshots**
![i18n_log_show_same_message](https://user-images.githubusercontent.com/9291161/83593463-66185b00-a58f-11ea-964e-25c647e81568.jpg)

**Comment by tigershi** [comment]
Can't emersion the error in the development environment

**Comment by tigershi** [comment]
This not a bug. This is caused by nginx cache
