### ISSUE TITLE
[BUG][Java Client] Wrong process when judging cache item expiration

### ISSUE THREAD

**Issue by Xiaochao8** [vmware/singleton#604]
There is a problem when judging cache item expiration.
There are 2 variables needed to judge expiration: maxAgeResponse and responseTimeStamp. These 2 variables should be gotten in a sync block to make sure they are matched.

**Comment by jessiejuachon** [comment]
This is now ready to test

**Comment by surite** [comment]
@Xiaochao8 could you please give more details about this issue, if there is not reproduce steps, please show code section with bug.

**Comment by Xiaochao8** [comment]
> @Xiaochao8 could you please give more details about this issue, if there is not reproduce steps, please show code section with bug.

@surite This is a multithread issue and can't be tested by normal test cases. I think we can close it if no issue is found during testing.
