### ISSUE TITLE
[REQUIREMENT][Java Client] Add capability of loading local formatting pattern files

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#623]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solution or feature you've considered.

**Additional context**

**Comment by jessiejuachon** [comment]
@gong-yu , @lyiyu66 , do we need to finish this (L2 offline mode) before creating a new official release build?
