### ISSUE TITLE
[BUG] [C# Client]The product name and version in the URL requested to the server are replaced by offline_resources_base_url when online and offline modes are provided.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#640]
**Describe the bug**
The product name and version in the URL requested to the server are replaced by offline_resources_base_url when online and offline modes are provided.
When online and offline urls have different product names or version, such as steps1, the request url http://localhost:8091/i18n/api/v2/translation/products/CSharpClient/versions/1.0.0/locales/de/components/RESX will become
http://localhost:8091/i18n/api/v2/translation/products/CSharp/versions/1.0.0/locales/de/components/RESX, User can't get the translation from online server .
The request to server url should ont be changed by offline_resources_base_url.

**To Reproduce**
1. Set config as below, make sure server and localbundle urls are provided.
online_service_url: http://localhost:8091/singleton/CSharpClient/1.0.0/
offline_resources_base_url: file:///d:/l10n/CSharp/1.0.0 (or offline_resources_base_url: CSharp/1.0.0)
2. Request a key with the locale only exist in online bundle:
Translation.SetCurrentLocale("fr");
String Currentlocale = Translation.GetCurrentLocale();
Sourcetest = Translation.CreateSource("RESX", "RESX.ARGUMENT")
String result = Translation.GetString(Currentlocale, Sourcetest);

**Expected behavior**
the return result should be fr translation from online bundle.

**Comment by jin-jasper** [comment]
The product names and versions of offline and online must be the same. If not, offline url is used becase only one is available.

**Comment by dleng-vmware** [comment]
Has this rule been decided yet？even so, if the configuration is as follows:
online_service_url: http://localhost:8091/singleton/CSharpClient/1.0.0/
offline_resources_base_url: file:///d:/l10n/CSharpClient/2.0.0
the version 2.0.0 exist in online bundle
it will be request to http://localhost:8091/i18n/api/v2/translation/products/CSharp/versions/2.0.0/locales/de/components/RESX,ruturn online translation

**Comment by lyiyu66** [comment]
The online url and offline url should be independent. They should not restrict each other.
