### ISSUE TITLE
[BUG] [Java Client]Get ClassCastException exception when getting pattern data with invalid locale or language&region in online mode.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#655]
**Describe the bug**
Failed to fallback to default locale when getting pattern data with invalid locale or language&region in online mode.
Example:
Invalid locale: aa
Invalid language&region: aa&AA

**To Reproduce**
1. Let "aa" as locale or "aa"&“AA” as language&region in below API to get related pattern data: 
formatCurrency()
formatPercent()
formatNumber()
formatDate()
2. java.lang.ClassCastException will be threw as attachment.

**Expected behavior**
No exception and fallback to default locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/51813046/87053168-3c102380-c234-11ea-8845-a6f0a9df1cdf.png)

**Comment by surite** [comment]
Test pass on commit 3b6f338c9c06dd6457baf6271eb2c21f7fed8aeb, no exception and fallback to default locale(test with non en locale too) when locale or language/region is invalid.
