### ISSUE TITLE
[BUG] [Java Client][BUG] [Java Client]Get java.lang.NullPointerException exception when getting pattern data from unreachable service in online mode.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#656]
**Describe the bug**

**To Reproduce**
1. Initial config with unreachable service url(https://notexist:8090) in below API to get related pattern data:
formatCurrency()
formatPercent()
formatNumber()
formatDate()
2.  java.lang.NullPointerException will be threw as screenshot below.

**Expected behavior**
No exception and fallback to default locale.

**Screenshots**
![image](https://user-images.githubusercontent.com/51813046/87054477-bf7e4480-c235-11ea-8358-d6c9162a7212.png)

**Comment by surite** [comment]
@huihuiw01 
Test on commit e043197ae11891f30df588193618f7fb5fa8c579, I think it should be tested under online offline mixed mode, right? And I still get error when executing following code:
g11n-java-client/src/main/java/com/vmware/vipclient/i18n/messages/api/opt/local/LocalPatternOpt.java   Line 27
CommonUtil.getCLDRLocale(locale, localePathMap, localeAliasesMap);

I did not find 'com.vmware.i18n.utils.CommonUtil'.

**Comment by surite** [comment]
After add 'singleton-i18n-patterns-core' to build dependencies, test pass.
