### ISSUE TITLE
[BUG] [Java Client]Failed to initialize client when initializeCache=true in pure offline mode.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#661]
**Describe the bug**
Failed to initialize client when initializeCache=true in pure offline mode.

**To Reproduce**
1. Set below in config file and no singleton service provided.
offlineResourcesBaseUrl = offlineBundles
initializeCache = true
2. Get cache after service initialization is done.

**Expected behavior**
Can initialize client and cache successfully during application startup when initializeCache=true in pure offline mode.

**Comment by jessiejuachon** [comment]
Fix is in [PR673](https://github.com/vmware/singleton/pull/673/). Requesting @Xiaochao8 to review and approve it.

**Comment by jessiejuachon** [comment]
@lyiyu66 , this is ready for testing.

**Comment by surite** [comment]
Test pass, cache can be initialized on pure offline mode.

**Comment by jessiejuachon** [comment]
Fixing bug related to offlinne mode when running an executable jar file.
https://github.com/vmware/singleton/pull/728
