### ISSUE TITLE
[BUG] [Java Client] If cache item is expired, and online bundle fetch failed, offline fetch is triggered.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#686]
**Describe the bug**
If cache item is expired, and online bundle fetch failed, offline fetch is triggered. 

**To Reproduce**

**Expected behavior**
Offline fetch should not be triggered. Overwrite the cache only if online bundle fetch is successful.

**Comment by jessiejuachon** [comment]
@lyiyu66 , please add the steps to reproduce in the description

**Comment by jessiejuachon** [comment]
@lyiyu66 this is ready for testing.

**Comment by surite** [comment]
@jessiejuachon  if 'Offline fetch should not be triggered', what should be return once getting translation? could you please give more details about the expected behavior?

**Comment by jessiejuachon** [comment]
@surite , if the cache is empty, then offline fetch should be triggered as fallback. And if it still failed, then fetch for fallback locale (online first, then offline if failed).

However, if the cache is already populated (from online) previously, then we do not want to overwrite it with offline bundles. Just use the previously cached data from the service.

**Comment by surite** [comment]
Verify on commit df4d476dbe3e6593be08f2f91bd3d8de58e99bd0, close it.
