### ISSUE TITLE
[BUG] [Go Client]Can't get updated component that only offline bundle exists at first when update this component in service and cache expired in mutiple mode.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#690]
**Describe the bug**
Can't get updated component that only offline bundle exists at first when update this component in service and cache expired in mutiple mode.
It also occured by GetStringMessage() method.

**To Reproduce**
1. Set config as below:
    "online_service_url": "http://localhost:8091",
    "offline_resources_base_url": "../testdata/localBundles",
    "default_locale": "zh-Hans"
2. The component "componentlocale" only exist in offline:
ommsg1, _ := translation.GetComponentMessages(name, version, "fr", "componentlocale")
3. Get one key's value from step2 returned result.
value, _ := commsg.Get("language")
4. Put the component "componentlocale" to online bundle
5. Repeat the request in step 2.
6. Repeat the request in step 2.
7. Repeat step 3.
Still get the offline translation rather than the updated translation in step 4.

**Expected behavior**
Should get the updated translation from online when cache is expired

**Comment by Xiaochao8** [comment]
There is a default expiration time 24 hours. when both online and offline are available, next try will be triggered in 24 hours.
So this isn't a bug.

**Comment by dleng-vmware** [comment]
Change the default expiration time to 60s in github.com/dleng-vmware/singleton, it will be triggered after 60s, So  it is't a bug.
