### ISSUE TITLE
[BUG] g11n-java-client-0.4.2 - TranslationMessage.getString2 - Translation value is changed to the key if ResourceBundle is not accessible.

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#712]
**Describe the bug**
In TranslationMessage.getString2, the key is assigned to 'source' if ResourceBundle is not accessible. When this happens, in getString, comparison of source and remoteEnMsg is applied, so the translation value is changed to the key, which is incorrect. The comparison should be skipped is source.equals(key).

**To Reproduce**
Use TranslationMessage.getString2 in a module where the ResourceBundle is not accessible. TranslationMessage.getString2 returns the key.

**Expected behavior**
TranslationMessage.getString2 must return the translation that was retrieved from the service which corresponds to the locale, component and key passed.

**Comment by surite** [comment]
Test done on https://repo1.maven.org/maven2/com/vmware/singleton/singleton-client-java/0.4.4/singleton-client-java-0.4.4.jar, no issue found.
