### ISSUE TITLE
[BUG] g11n-java-client TranslationMessage.getMessage for non-supported locales always triggers a request to VIP service  in a separate thread 

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#717]
**Describe the bug**
For non-supported locales, the cached fallback locale messages are returned immediately. This is the correct behavior. However, a separate thread is simultaneously launched to try to fetch the messages for the requested locale from the  VIP service. This done so that at runtime, in case support for the requested locale is added, the client application will be able to get the messages from VIP service. However, the thread is launched for every request, which does not change the result, but may be expensive in terms of application resource.

**To Reproduce**
1. Send request for a non-supported locale. Notice that a request to VIP is triggered every time.

**Expected behavior**
Requested locale must use the same maxAgeMillis as the fallback locale, but must have its own timestamp (and therefore, its own expiration time).
Send request to VIP service only after cache for the requested locale has expired.

**Comment by lyiyu66** [comment]
The issue has been fixed with commit e8c3dde63ae25f36f967cd89435cbf26ef7457e5. Hence closing.
