### ISSUE TITLE
[Security][JAVA Client] Upgrade dependency libiraies to latest version

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#737]
In Singleton JAVA Client, 2dependency libraries are out of date, please upgrate them:
- jackson-databind (2.6.2) --> 2.11.2
- commons-collections (3.2) --> 3.2.2

**Comment by linr211** [comment]
Is it only required on master branch's codes, right? I don't see the libraries on 0.4.x branch(old codes).

**Comment by nannany00** [comment]
@linr211, it's not master branch, it's g11n-java-client branch.
