### ISSUE TITLE
[BUG] g11n-java-client - Performance impact on the very first L3 fetch for a non-supported locale 

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#754]
**Describe the bug**
For supported locales, cache can be populated at application start up to avoid performance hit of having to query the service first. However, when the requested locale is not supported, that means cache hasn't been populated for it. What will happen is the application will first try to fetch from service (if configured), then from offline bundles, then return the fallback locale data.

**To Reproduce**
1. Start application with initializeCache=true
2. Trigger (first) request from user/browser for a non-supported locale
3. Notice that application has to wait for service request and offline fetch to fail first before returning data of fallback locale.

**Expected behavior**
 Return translations in fallback locale immediately (from cache, instead of trying to fetch from service first). No request to service will be sent.

**Comment by jessiejuachon** [comment]
@surite , could you also verify the bug if you have time? Thanks.

**Comment by surite** [comment]
@jessiejuachon is it fixed? I see you open this issue just now.

**Comment by jessiejuachon** [comment]
@surite , it is not fixed yet. I just found it. I just wanted to confirm the validity of the bug with you (or anyone doing QE).

**Comment by jessiejuachon** [comment]
Moved this to Sprint 90 due to overlapping changes with PR782 (issue 781) in current Sprint.

**Comment by jessiejuachon** [comment]
@lyiyu66 , FYI for testing.
