### ISSUE TITLE
[Security][JAVA Client] Upgrade dependency libiraies to latest version

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#779]
In Singleton JAVA Client, 1 dependency librariry is out of date, please upgrate it:
- jackson (2.6.2) --> 2.11.2

**Comment by Xiaochao8** [comment]
This is from singleton-i18n-patterns-core. Chaoq, could you help look  at this?

\--- com.vmware.singleton:singleton-i18n-patterns-core:0.4.0
     +--- commons-collections:commons-collections:3.2
     +--- com.googlecode.json-simple:json-simple:1.1.1 (*)
     +--- com.fasterxml.jackson.core:jackson-databind:2.6.2
     |    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.0
     |    \--- com.fasterxml.jackson.core:jackson-core:2.6.2
