### ISSUE TITLE
[BUG] [Python Client]Can't get "zh-Hans" or "zh-Hant" translation by get_string()

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#787]
**Describe the bug**
Can't get "zh-Hans" or "zh-Hant" translation by get_string(), the result is source_locale string.
The issue occurs in all modes
**To Reproduce**
1.Set config as below in config.yml 
offline_resources_base_url: file://d:/l10ntest/PythonClient/2.0.0/
2. The locale "zh-Hans" exist in offline bundle
        I18n.add_config_file('sample_offline_disk.yml')
        self.rel = I18n.get_release(PRODUCT, VERSION)
        translation1 = self.rel.get_translation()
        tran1 = translation1.get_string("about","about.message",locale = "zh-Hans")
**Expected behavior**
tran1 should be the translation of "zh-Hans" rather than the string of "en-US"

**Comment by lyiyu66** [comment]
It will return fr translation even there is fr-CA translation file.
