### ISSUE TITLE
[BUG] [Python Client]IndexError pops up when Translation.get_string(componment, key, format_items) with Index of source string greater than the size of format_items.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#789]
**Describe the bug**
IndexError pops up when Translation.get_string(componment, key, format_items) with Index of source string greater than the size of format_items.

**To Reproduce**
1. the test string is "test fr the {1} to {0} and {2}"
2. trans = translation.get_string("about", "about.test", format_items = ["a","b"])
IndexError: tuple index out of range

**Expected behavior**
Can handle and no exception pop up if Index greater than the size of format_items.

**Comment by jin-jasper** [comment]
IndexError  exception is standard python exception. When input of get_string is wrong, exception should occur.

**Comment by dleng-vmware** [comment]
After discussion, it is considered feasible to show the current error information to users. So, It's not a bug.
