### ISSUE TITLE
[BUG] [Java Client]Plurals pattern can't fallback to default locale when translation is using default locale's.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#790]
**Describe the bug**
When requested locale doesn't has corresponding translation, it will fallback to default locale's translation. But the plurals pattern still is requested locale's.
Example:
re

**To Reproduce**
1. Set requested locale = ar, which has many categories in plural pattern.
"pluralRule-count-few": "n % 100 = 3..10 @integer 3~10, 103~110, 1003, … @decimal 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 103.0, 1003.0, …",
2. Set default locale = zh-Hans in config file.
3. There is no translation in ar but has zh-Hans:
The translation of key "plural.key":"{0, plural,one {\"{1}\"上有一个文件。} two {\"{1}\" 具有2个文件。}  few {\"{1}\" 具有三个文件。} other {\"{1}\"上有#个文件。}}"}
Locale ARLocale = new Locale("ar");
String pluralKey = "plural.key";
Object[] testArg5 = {3, "MyDisk"};
String pluralMessage5 = translation.getMessage(ARLocale, component, pluralKey, testArg5);
log.verifyEqual("other category + default locale translation:  ", pluralMessage5, "\"MyDisk\" 有3个文件。");
4. Currently, actual is {"MyDisk" 具有三个文件。} in few category.

**Expected behavior**
It should use other category's translation("MyDisk" 有3个文件。) since there is no few category in zh-Hans's plural pattern.

**Comment by lyiyu66** [comment]
The plural pattern can fallback to default locale, but it introduces an new issue that the number format is using default locale when plurals engaged.
Still use the example in above, just change the argument: 
Object[] testArg5 = {3000, "MyDisk"};

Current result is {"MyDisk"上有3,000个文件。} : the group symbol is using zh-CN's pattern.
Expected result is {"MyDisk"上有3٬000个文件。}: the group symbol should use ar's pattern as there has ar pattern in Singleton.

**Comment by huihuiw01** [comment]
Test ICU4J library, the calculation of plural case and display format of number use the same locale, that means when translation fallback, plural format either use requested locale or default locale. According to our initial design we choose to use default locale. So both the plural case and number display as default locale. It's correct behavior, hence mark this bug as invalid.

It doesn't make sense to calculate plural with default locale, and display number with requested locale.

**Comment by lyiyu66** [comment]
Beside of currencies symbol, other patterns fetch base on language in ICU4j, there is no query that plurals and number pattern use the same locale in ICU4j library. But in Singleton, the formatter of pattern all base on region except plurals/dateField. If keep as it is, the number format will have 2 types, one follows language in plurals sentences, another follows region in common usage. That may have confusion.

**Comment by lyiyu66** [comment]
After discussion, if the number formatting of plurals sentence changes to follow region, it also have confusion as the locale of format isn't consistent with the locale of sentence translation. Keep the current behavior as it is. Will have a task to do further discussion/investigation for improvement.

**Comment by lyiyu66** [comment]
Remove the invalid tag as the initial behavior in description is valid.
