### ISSUE TITLE
[BUG] Java client returns fr messages for requested locale is fr-CA, even if fr-CA locale is supported

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#827]
**Describe the bug**
Java client returns fr messages for requested locale is fr-CA, even if fr-CA locale is supported

**To Reproduce**
1. Set up VIP service or offline bundles to have both fr and fr-CA bundles. Make a slight difference to one of the messages.
2. Request for fr-CA (TranslartionMessage.getMessage(Locale.forLanguageTag("fr-CA", component, key);
3. Notice that fr message is returned instead of fr-CA.

**Expected behavior**
fr-CA message must be returned

**Comment by jessiejuachon** [comment]
Coincidentally resolved by https://github.com/vmware/singleton/pull/823

**Comment by jessiejuachon** [comment]
@lyiyu66 , FYI for testing

**Comment by lyiyu66** [comment]
The issue is not reproducible on commit https://github.com/vmware/singleton/commit/64dfd0981e23c7db8b80431d9f724c5f7988b971
