### ISSUE TITLE
[BUG] L2 cache items are being marked as "not expired" by extending the timestamp even if fetch from data source failed

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#841]
**Describe the bug**
Incorrectly marking a stale cacheItem as not expired, even if failed to refresh the data (i.e. the same data didn't change and is actually still expired)
Faulty code: `cacheItem.set(System.currentTimeMillis());`
Instances: 
RemoteLocaleOpt, LocalLocaleOpt, LocalPatternOpt, RemotePatternOpt

**To Reproduce**
1. Enable online mode only.
2. In the client, request L2 for a locale so that a corresponding cache item will be created.
3. Wait for cache item's expiration (you may shorten the cache max-age in the service so not to wait for a long time) 
4. Make VIP service unavailable/down.
5. In the client, request for the same locale's L2 data. Notice that the service request will fail.
6. Request for the same locale's L2 data. Notice that no service request is sent this time, which means the request in #5 has updated the cache item's timestamp even if the request failed.

**Expected behavior**
Cache item's timestamp should not have been updated in #5 so that it will remain "expired". A service request should have been sent in #6.

**Comment by lyiyu66** [comment]
The issue and specific Windows issue have been fixed with commit 3678872.
