### ISSUE TITLE
[DESIGN DISCUSSION] Differences/similarities in fallback behavior between L2 and L3

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#843]
**Is your feature request related to a problem? Please describe.**
After adding offline mode support for L2, we recognized that the original design only took L3 into consideration, and therefore, some L2-specific use cases may have been missed. This is a placeholder for discussing any item that is related to this.

**Describe the solution you'd like**
As much as possible, maintain a single workflow design for both L2 and L3. If and only if a variation is necessary for specific cases do we make an exception.

**Comment by jessiejuachon** [comment]
Items discussed so far:
https://github.com/vmware/singleton/issues/841

**Comment by huihuiw01** [comment]
After discussion, the final conclusion for L2 fallback is: 
requested locale -> default locale

And L2 data for default locale should be always available, if fallback to default locale fails, bug should be reported by QE.
