### ISSUE TITLE
[BUG] [Service]Add a switch for configuration (source.collect.locales)

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#851]
**Describe the bug**
A configuration item (source.collect.locales) is configured to define the locale of source collection. 
Please add a switch to control this configuration;

If this item is configured, and the request locale is not match with the config, change the response message friendly.
Now, it's 400: incorrect locale(only support letters, numbers, dot)
It should be: 400: source collection locale only allows {0}.

**Expected behavior**
Add a switch for this configuraiton item.

**Comment by tigershi** [comment]
because the validate no use Scene， we decide to remove it
