### ISSUE TITLE
[BUG] change the l10n resource collection url to gateway pattern 

### ISSUE THREAD

**Issue by tigershi** [vmware/singleton#873]
If want to expose the l10n API to VDP gateway need to set the URL to start with "/ i18n/l10n"

**Comment by lyiyu66** [comment]
Tested with commit ac480a59b63a2868dce775d5a8c882124c0b93f6, below APIs don't use /i18n/l10n/api/.... please change them as well:

POST /l10n/api/v1/source/products/{productName}/versions/{version}
GET /l10n/api/v1/source/products/{productName}/components/{component}/keys/{key}
POST /l10n/api/v1/source/products/{productName}/components/{component}/keys/{key}

![image](https://user-images.githubusercontent.com/51813046/100739072-84152a00-3411-11eb-9ad3-a5512cb8f8f4.png)

**Comment by nannany00** [comment]
These 3 APIs mentioned above are not public, no need to change to new path.
