### ISSUE TITLE
[ENHANCEMENT and BUG] Non-blocking getSupportedLocales when fetching messages

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#877]
**Is your feature request related to a problem? Please describe.**
There are 2 issues:
1. Message fetch fails if getSupportedLocales failed, even if messages are available in remote/local dataSource. 
This should not be the case because getting the list of supported locales is only primarily used for caching and performance.
2. Message fetch is delayed if supported locales hasn't been cached.

**Describe the solution you'd like**
Even if getSupportedLocales had failed (e.g. VIP service was temporarily down), message fetch should not be blocked.
Even if the set of supported locales is not yet in cache (e.g. supported locales cache is not initialized (i.e initializeCache=false)), message fetch should not have to wait. getSupportedLocales should be done in a separate concurrent thread.

**Comment by lyiyu66** [comment]
The issue and specific Windows issue have been fixed with commit 3678872.
