### ISSUE TITLE
[BUG] Java client offline mode fails in nested-jar applications such as Spring Boot (initially reported by the Atlas team)

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#882]
**Describe the bug**
Java client offline mode fails in nested-jar applications such as Spring Boot.

After investigation, the root cause seems to be the following:
1. The java client library tries to walk the file system when getting the list of supported locales. This fails when the file system is in a nested jar.  Such is the case in Spring boot applications where the offline bundles directory may exist inside dependency jars which under BOOT-INV/libs. This is related to https://github.com/vmware/singleton/issues/877
2. The java client library tries to access the file system when reading the bundle (code is in LocalMessagesOpt.getComponentMessages). This fails when the file system is in a nested jar. 

**To Reproduce**
1. Build and run the https://github.com/vmware/singleton/tree/g11n-java-client/sample-client-app/sample-app-with-shared-lib as a Spring boot app:
 "gradle -b build-spring-boot.gradle build"
"java -jar ./build/libs/sample-spring-boot-with-shared-lib-1.0.jar"
Note: The build-spring-boot.gradle file has to be added. See https://github.com/vmware/singleton/pull/883.
3. See the exception.

**Expected behavior**
No exceptions.
Solutions:
1. Even if getSupportedLocales had failed, message fetch should not be blocked. This is related to issue https://github.com/vmware/singleton/issues/877
Note: Java 11 and below does not support any way to "walk" the file system of a nested jar. Hence, getSupportedLocales is expected to fail for nested jars, but should not block message fetch from resource bundle.
2. Use getResourceAsStream in LocaleMessagesOpt.getComponentMessages to read the local message bundle which should work for non-jar, jar and nested-jar applications.

**Additional context**
This was initially reported by the Atlas team.

**Comment by lyiyu66** [comment]
@jessiejuachon 
Checked with build on commit 8d7af99406fccd673f1fe205b48a33eae19f3af7, there is an exception about "Failed to get any message for key: global_test_username of component default, requested locale: fr". Looks it can't get the translation from offlineBundles.

![image](https://user-images.githubusercontent.com/51813046/101336848-e9579800-38b5-11eb-9727-8e6cecf67772.png)

**Comment by jessiejuachon** [comment]
Hi Yiyu! I just did a fresh git clone of the repo and checked out the commit. I did not get an error.
![Screen Shot 2020-12-07 at 8 39 33 AM](https://user-images.githubusercontent.com/5719531/101378394-e3d36100-3867-11eb-8c81-b7e676a9e1aa.png)

**Comment by jessiejuachon** [comment]
![Uploading Screen Shot 2020-12-07 at 8.51.27 AM.png…]()

**Comment by jessiejuachon** [comment]
This is what I have before running "java -jar ..."
![Screen Shot 2020-12-07 at 8 51 27 AM](https://user-images.githubusercontent.com/5719531/101379828-9657f380-3869-11eb-929b-eb49c7f85a96.png)

**Comment by lyiyu66** [comment]
Hi @jessiejuachon , as we talked in Slack, the issue can't be reproducible on Linux.

**Comment by lyiyu66** [comment]
The issue and specific Windows issue have been fixed with commit 36788729a6058d3d7a1ec3c12b4d64eb3aee6043.
