### ISSUE TITLE
[BUG] [L10n Service] token validation shouldn't intercept APIs that used for l10n Agent

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#885]
**Describe the bug**
When enable token validation for source collection, there's need to provide token for some APIs; but there're some APIs that no need token validation, just like record APIs that to record the update time for each products.

**To Reproduce**
1. Start the latest Singleton L10n Service Build with token validation enabled
2. To visit /l10n/api/v1/source/records
3. See error
```
{"code":401,"message":"Token validation failed"}
```

**Expected behavior**
Can get the detail response.

**Comment by lyiyu66** [comment]
Issue is fixed on commit ac480a59b63a2868dce775d5a8c882124c0b93f6.
![image](https://user-images.githubusercontent.com/51813046/100834720-5bd80a80-34a7-11eb-9938-2d05058d0978.png)
