### ISSUE TITLE
[REQUIREMENT] Downloadable offline resource bundle zip + sample app

### ISSUE THREAD

**Issue by jessiejuachon** [vmware/singleton#891]
**Is your feature request related to a problem? Please describe.**
Offline resource bundle zip is not available for download.

**Describe the solution you'd like**
1. For every new product-version, deliver a downloadable offline resource bundle zip with folder hierarchy:
< component >
< component >/messages_<locale>.json

2. Downloadable from artifactory (e.g. atlas-1.0.0.zip).

To test: Update the sample app to use a sample downloadable zip from VIP test/dev.

**Comment by junw-33455432** [comment]
Hi Jessie, as bundle zip in Maven stage repository has an expire time, I've uploaded the package to SNAPSHOT repo, please find it from here: https://oss.sonatype.org/content/repositories/snapshots/com/vmware/singleton/singleton-bundle/SampleProject/maven-metadata.xml
