### ISSUE TITLE
[Documentation][Singleton Service] Update information about how to use AWS S3 access key

### ISSUE THREAD

**Issue by gong-yu** [vmware/singleton#904]
Tell users how to encrypt AWS S3 access key, and how to configure the key to be used in Singleton Service

**Comment by tigershi** [comment]
https://confluence.eng.vmware.com/display/GQ/How+to+use+encrypt+AWS+S3+access+key+and+secretkey+in+singleton+service

**Comment by tigershi** [comment]
I have updated the document to website branch
