### ISSUE TITLE
[Security] Please upgrade dependency libraries to latest version

### ISSUE THREAD

**Issue by nannany00** [vmware/singleton#921]
In Singleton Service build, below dependency librariries are out of date, please upgrate it:
**tomcat** (9.0.39) --> 10.0.0
**jackson-databing** (2.10.0.pr1) --> 2.11.4
**httpcomponents-client** (4.5.12) --> 4.5.13
**guava** (29.0-jre) -->30.1-jre

**Comment by tigershi** [comment]
we upgrade the tomcat (9.0.39) --> 9.0.41

**Comment by lyiyu66** [comment]
API regression test is passed with commit 639f41d6ab17c1d424fd7e28b08ba7d48cf2f2bc
