### ISSUE TITLE
[BUG] [Service]Singleton service version info isn't loaded when requesting unsupported product/version in about API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#934]
**Describe the bug**
Build with commit: 5414eb6939a4c4414f65cf091bc67e4737e38f07
Service version info isn't loaded when requesting unsupported product/version in about API.

**To Reproduce**
1. Go to 'https://localhost:8090/i18n/api/v2/about/version?productName=JavaClientx&version=1.0'
2. Check the service name in server response: 
```
{
  "code" : 400,
  "message" : "The product 'JavaClientx' is NOT supported yet!",
  "serverTime" : ""
}
```

**Expected behavior**
Singleton service version info should be loaded anytime since service is running normally. Invalid product/version request should not block service info displaying.

In addition, it will be better to have corresponding behavior/response when requesting different kind of product/version(may we can use response code and message to distinguish different status):
1. product isn't in bundle white list, it should clarify "Product is not supported yet."
2. no version.json file under requested product/version folder, it should clarify "Failed to get version info for product/version"

**Comment by huihuiw01** [comment]
After discussion this behavior is by design, not a bug, so needn't fix it.

**Comment by lyiyu66** [comment]
Closing the issue according comment https://github.com/vmware/singleton/issues/934#issuecomment-759355350
