### ISSUE TITLE
[BUG] [Service][lite]Product allow list doesn't work in Singleton I18n Service

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#936]
**Describe the bug**
Build with commit 5414eb6939a4c4414f65cf091bc67e4737e38f07
Singleton Service has a feature, **allow list**, only the data can be returned when request the product in the white list. But now, it doesn't work in Singleton bundle i18n build. 

**To Reproduce**
1. Start the latest Singleton bundle i18n build;
2. Go to any API related to translation: GET /i18n/api/v2/locale/supportedLanguageList Get the supported language list 
Check the existing white list config *bundle.json*:
```
{
"Testing": ["1.0.0"]
}
```
Request Parameters:
```
productName: temp
version: 1.0.0
```
Response:
```
{
  "response": {
    "code": 404,
    "message": "Failed to get locale list for temp/1.0.0",
    "serverTime": ""
  },
  "signature": "",
  "data": ""
}
```

**Expected behavior**
The response should be:
```
{
  "code" : 400,
  "message" : "The product 'temp' is NOT supported yet!",
  "serverTime" : ""
}
```

**Comment by huihuiw01** [comment]
After sync with @gong-yu and @tigershi, lite build is designed for on-premise product, which requires as less footprint as better, so lite build doesn't include the unnecessary feature such as allow list, so this is not a bug.

**Comment by lyiyu66** [comment]
Closing it according to above comment https://github.com/vmware/singleton/issues/936#issuecomment-839643626.
