### ISSUE TITLE
[BUG] [Service]Failed to get plurals data if language is valid but region is invalid in patterns API.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#978]
**Describe the bug**
Tested on build with commit af12ee44a66854e33eb4e104d5133e1be3789053
Failed to get plurals data if language is valid but region is invalid in patterns API
/i18n/api/v2/formatting/patterns

**To Reproduce**
1. Go to 'https://localhost:8090/i18n/api/v2/formatting/patterns?language=en&region=BCD&scope=plurals
'
2. See the response:
`{
  "response": {
    "code": 404,
    "message": "Not Found",
    "serverTime": ""
  },
  "signature": "",
  "data": "'No mapping language found for region!"
}`

**Expected behavior**
Can get plurals data according to the valid language.

**Comment by JiLiang888** [comment]
pass
![image](https://user-images.githubusercontent.com/82644009/122874711-e0b44400-d365-11eb-8b68-22b2192fed1b.png)
