### ISSUE TITLE
[BUG] [Python Client]The value of source that user enters is not validated when offline mode is supported.

### ISSUE THREAD

**Issue by dleng-vmware** [vmware/singleton#981]
**Describe the bug**
The value of source that user enters is not validated when offline mode is supported.

**To Reproduce**
1.Set config as below in config.yml
  offline_resources_base_url: file://d:/l10ntest/PythonClient/2.0.0/
  log_path: ./log/
2. The key exist in offline bundle,but the source is different from what user typed
        I18n.add_config_file('sample_offline_disk.yml')
        I18n.set_current_locale(“fr")
        self.rel = I18n.get_release(PRODUCT, VERSION)
        translation1 = self.rel.get_translation()
        trans1 = translation1.get_string("about","about.message",source = "123")////The source is not 123 in offline bundle
        the result trans1 is fr translation that exist in offline bundle

**Expected behavior**
the result trans1 should be request_source "123".

**Comment by jin-jasper** [comment]
In offline case, translation comes from local resources. And they supposed to be right when released.

**Comment by lyiyu66** [comment]
What about during development? It won't return to latest source.

**Comment by jin-jasper** [comment]
offline mode doesn't need to validate source.

**Comment by lyiyu66** [comment]
During the development, the source may has been changed. If no comparation between source&en(assume the source language is in English), it always get old translation.

**Comment by dleng-vmware** [comment]
This bug has been fixed in version 0.6.0.1
