### ISSUE TITLE
[BUG] [Service]White list doesn't work on PUT/POST APIs.

### ISSUE THREAD

**Issue by lyiyu66** [vmware/singleton#985]
**Describe the bug**
Build with commit 104019846f77b6de8939594bb0c7fa9ba5b0ee27
White list doesn't work on PUT/POST APIs.
POST APIS:
/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys
/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys/{key}
/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}
PUT API:
/i18n/api/v2/translation/products/{productName}/versions/{version}

**To Reproduce**
Take the api(/i18n/api/v2/translation/products/{productName}/versions/{version}/locales/{locale}/components/{component}/keys) as example
1. Go to 'https://localhost:8090/i18n/api/v2/translation/products/postSourceUsingPOST/versions/1.0/locales/en/components/default/keys?collectSource=true
'
sourceSet:
```
[
  {
    "commentForSource": "string",
    "key": "string",
    "source": "string"
  }
]
```
products=postSourceUsingPOST #this product name is new product, it isn't in Bundle.json file.

2. See response:
```
{
  "response": {
    "code": 200,
    "message": "OK",
    "serverTime": ""
  },
  "signature": "",
  "data": "Recieved the sources and comments(please use translation-product-component-api to confirm it)."
}
```

**Expected behavior**
White list should be worked, should say this product is not supported yet.

**Comment by huihuiw01** [comment]
Discussed with Colin, he thinks white list shouldn't apply to POST API as it will block  developer do testing for source collection before registration(which means being added to white list).

And registration need change white list at runtime, it's not reasonable. The final solution is product send token when do source collection, which is implemented by Resource Service.
So he suggest hold on fix it and wait for the registration feature of Resource Service be online.

**Comment by lyiyu66** [comment]
Verified with commit 30d4f9326a08cf696816bf2980b5bbe18c5832d5, allow list does work well on mentioned APIs.
Hence closing.
